/** Compact Idleon Toolbox catalogs used by Dashboard account alerts. Generated from IT website-data. */
export type StampGoldInfo = { rawName: string; base: number; pow: number; req: number };
export type NamedRaw = { rawName: string; name: string };
export type VialInfo = { name: string; mainItem: string; liquid: string };
export type RefineryCost = { rawName: string; quantity: number };
export type RefinerySaltInfo = { rawName: string; saltName: string; cost: RefineryCost[] };
export type SigilInfo = { name: string; boostCost: number; jadeCost: number; etherealCost: number; eclecticCost: number };
export type PoppyUpgrade = { name: string; x1: number; x2: number; x3: number };

export const STAMP_GOLD: (StampGoldInfo | null)[][] = [
  [
    { rawName: "StampA1", base: 10, pow: 1.2, req: 5 },
    { rawName: "StampA2", base: 15, pow: 1.2, req: 5 },
    { rawName: "StampA3", base: 30, pow: 1.2, req: 5 },
    { rawName: "StampA4", base: 50, pow: 1.3, req: 4 },
    { rawName: "StampA5", base: 50, pow: 1.3, req: 5 },
    { rawName: "StampA6", base: 50, pow: 1.3, req: 5 },
    { rawName: "StampA7", base: 50, pow: 1.3, req: 4 },
    { rawName: "StampA8", base: 50, pow: 1.3, req: 3 },
    { rawName: "StampA9", base: 50, pow: 1.3, req: 2 },
    { rawName: "StampA10", base: 50, pow: 1.3, req: 4 },
    { rawName: "StampA11", base: 50, pow: 1.3, req: 2 },
    { rawName: "StampA12", base: 50, pow: 1.3, req: 4 },
    { rawName: "StampA13", base: 50, pow: 1.35, req: 2 },
    { rawName: "StampA14", base: 75, pow: 1.32, req: 3 },
    { rawName: "StampA15", base: 300, pow: 1.38, req: 2 },
    { rawName: "StampA16", base: 2000, pow: 1.33, req: 4 },
    { rawName: "StampA17", base: 5000, pow: 1.36, req: 5 },
    { rawName: "StampA18", base: 2500, pow: 1.3, req: 5 },
    { rawName: "StampA19", base: 3000, pow: 1.3, req: 6 },
    { rawName: "StampA20", base: 10000, pow: 1.3, req: 3 },
    { rawName: "StampA21", base: 2200, pow: 1.305, req: 7 },
    { rawName: "StampA22", base: 10000, pow: 1.3, req: 3 },
    { rawName: "StampA23", base: 10000, pow: 1.34, req: 10 },
    { rawName: "StampA24", base: 1550, pow: 1.36, req: 3 },
    { rawName: "StampA25", base: 15000, pow: 1.33, req: 5 },
    { rawName: "StampA26", base: 10000, pow: 1.32, req: 10 },
    { rawName: "StampA27", base: 25000, pow: 1.39, req: 4 },
    { rawName: "StampA28", base: 2000, pow: 1.36, req: 2 },
    { rawName: "StampA29", base: 2000000, pow: 1.43, req: 6 },
    { rawName: "StampA30", base: 3000000, pow: 1.47, req: 10 },
    { rawName: "StampA31", base: 1500000, pow: 1.4, req: 10 },
    { rawName: "StampA32", base: 1000000, pow: 1.4, req: 15 },
    { rawName: "StampA33", base: 100000000, pow: 1.4, req: 7 },
    { rawName: "StampA34", base: 100000000, pow: 1.4, req: 7 },
    { rawName: "StampA35", base: 100000000, pow: 1.4, req: 7 },
    { rawName: "StampA36", base: 100000000, pow: 1.4, req: 10 },
    { rawName: "StampA37", base: 200000000, pow: 1.43, req: 10 },
    { rawName: "StampA38", base: 10000000, pow: 1.43, req: 10 },
    { rawName: "StampA39", base: 25000000, pow: 1.36, req: 2 },
    { rawName: "StampA40", base: 2500000000, pow: 1.36, req: 10 },
    { rawName: "StampA41", base: 66000000000, pow: 1.36, req: 15 },
    { rawName: "StampA42", base: 2200000000000, pow: 1.36, req: 10 },
    { rawName: "StampA43", base: 660000000000000, pow: 1.36, req: 15 },
    { rawName: "StampA44", base: 6.6e+16, pow: 1.45, req: 15 }
  ],
  [
    { rawName: "StampB1", base: 10, pow: 1.2, req: 10 },
    { rawName: "StampB2", base: 10, pow: 1.2, req: 10 },
    { rawName: "StampB3", base: 50, pow: 1.3, req: 5 },
    { rawName: "StampB4", base: 50, pow: 1.3, req: 10 },
    { rawName: "StampB5", base: 10000, pow: 1.3, req: 5 },
    { rawName: "StampB6", base: 50, pow: 1.3, req: 10 },
    { rawName: "StampB7", base: 20000, pow: 1.3, req: 5 },
    { rawName: "StampB8", base: 50, pow: 1.3, req: 10 },
    { rawName: "StampB9", base: 80, pow: 1.35, req: 5 },
    { rawName: "StampB10", base: 35000, pow: 1.4, req: 10 },
    { rawName: "StampB11", base: 80, pow: 1.35, req: 5 },
    { rawName: "StampB12", base: 50000, pow: 1.36, req: 10 },
    { rawName: "StampB13", base: 800, pow: 1.29, req: 4 },
    { rawName: "StampB14", base: 1250, pow: 1.28, req: 5 },
    { rawName: "StampB15", base: 1000, pow: 1.3, req: 5 },
    { rawName: "StampB16", base: 2500, pow: 1.3, req: 2 },
    { rawName: "StampB17", base: 1000, pow: 1.32, req: 5 },
    { rawName: "StampB18", base: 1500, pow: 1.33, req: 5 },
    { rawName: "StampB19", base: 1000, pow: 1.3, req: 5 },
    { rawName: "StampB20", base: 1500, pow: 1.33, req: 5 },
    { rawName: "StampB21", base: 1000, pow: 1.3, req: 8 },
    { rawName: "StampB22", base: 1500, pow: 1.3, req: 5 },
    { rawName: "StampB23", base: 1000, pow: 1.3, req: 8 },
    { rawName: "StampB24", base: 1500, pow: 1.3, req: 5 },
    { rawName: "StampB25", base: 7500, pow: 1.3, req: 10 },
    { rawName: "StampB26", base: 10000, pow: 1.3, req: 5 },
    { rawName: "StampB27", base: 12500, pow: 1.3, req: 3 },
    { rawName: "StampB28", base: 15000, pow: 1.3, req: 3 },
    { rawName: "StampB29", base: 10000, pow: 1.3, req: 3 },
    { rawName: "StampB30", base: 10000, pow: 1.3, req: 4 },
    { rawName: "StampB31", base: 15000, pow: 1.3, req: 3 },
    { rawName: "StampB32", base: 50000, pow: 1.5, req: 4 },
    { rawName: "StampB33", base: 7500, pow: 1.3, req: 10 },
    { rawName: "StampB34", base: 15000, pow: 1.3, req: 2 },
    { rawName: "StampB35", base: 10000, pow: 1.3, req: 2 },
    { rawName: "StampB36", base: 6000, pow: 1.3, req: 6 },
    { rawName: "StampB37", base: 1000000, pow: 1.35, req: 15 },
    { rawName: "StampB38", base: 1000000, pow: 1.35, req: 15 },
    { rawName: "StampB39", base: 1000000, pow: 1.35, req: 10 },
    { rawName: "StampB40", base: 1000000, pow: 1.4, req: 10 },
    { rawName: "StampB41", base: 1000000, pow: 1.4, req: 15 },
    { rawName: "StampB42", base: 1000000, pow: 1.35, req: 10 },
    { rawName: "StampB43", base: 500000000, pow: 1.35, req: 5 },
    { rawName: "StampB44", base: 500000000, pow: 1.35, req: 5 },
    { rawName: "StampB45", base: 500000000, pow: 1.35, req: 8 },
    { rawName: "StampB46", base: 800000000, pow: 1.35, req: 10 },
    { rawName: "StampB47", base: 800000000, pow: 1.35, req: 2 },
    { rawName: "StampB48", base: 100000000000, pow: 1.37, req: 5 },
    { rawName: "StampB49", base: 50000000000, pow: 1.37, req: 8 },
    { rawName: "StampB50", base: 20000000000, pow: 1.37, req: 10 },
    { rawName: "StampB51", base: 50000000000, pow: 1.37, req: 8 },
    { rawName: "StampB52", base: 60000000000, pow: 1.37, req: 8 },
    { rawName: "StampB53", base: 800000000000, pow: 1.37, req: 8 },
    { rawName: "StampB54", base: 12000000000000, pow: 1.37, req: 8 },
    { rawName: "StampB55", base: 1200000000000000.0, pow: 1.37, req: 8 },
    { rawName: "StampB56", base: 1200000000000000.0, pow: 1.37, req: 8 },
    { rawName: "StampB57", base: 1200000000000000.0, pow: 1.37, req: 8 }
  ],
  [
    { rawName: "StampC1", base: 500, pow: 1.32, req: 10 },
    { rawName: "StampC2", base: 4000, pow: 1.28, req: 4 },
    { rawName: "StampC3", base: 800, pow: 1.31, req: 10 },
    { rawName: "StampC4", base: 1500, pow: 1.33, req: 10 },
    { rawName: "StampC5", base: 1000, pow: 1.33, req: 10 },
    { rawName: "StampC6", base: 1500, pow: 1.305, req: 5 },
    { rawName: "StampC7", base: 3000, pow: 1.3, req: 4 },
    { rawName: "StampC8", base: 1000, pow: 1.32, req: 5 },
    { rawName: "StampC9", base: 1200, pow: 1.31, req: 10 },
    { rawName: "StampC10", base: 5000000000000, pow: 1.3, req: 10 },
    { rawName: "StampC11", base: 30000, pow: 1.5, req: 10 },
    { rawName: "StampC12", base: 1000000, pow: 1.32, req: 12 },
    { rawName: "StampC13", base: 2000, pow: 1.4, req: 2 },
    { rawName: "StampC14", base: 4000, pow: 1.35, req: 2 },
    { rawName: "StampC15", base: 40000, pow: 1.35, req: 2 },
    { rawName: "StampC16", base: 300000000, pow: 1.4, req: 2 },
    { rawName: "StampC17", base: 50, pow: 1.3, req: 2 },
    { rawName: "StampC18", base: 50, pow: 1.3, req: 2 },
    { rawName: "StampC19", base: 10000, pow: 1.3, req: 2 },
    { rawName: "StampC20", base: 12500, pow: 1.3, req: 2 },
    { rawName: "StampC21", base: 1000000, pow: 1.6, req: 3 },
    { rawName: "StampC22", base: 25000000, pow: 1.52, req: 5 },
    { rawName: "StampC23", base: 25000000, pow: 1.52, req: 8 },
    { rawName: "StampC24", base: 2000000000, pow: 1.72, req: 20 },
    { rawName: "StampC25", base: 2000000000, pow: 1.72, req: 15 },
    { rawName: "StampC26", base: 2e+18, pow: 4.5, req: 1 },
    { rawName: "StampC27", base: 20000000000000, pow: 1.72, req: 15 }
  ]
];

export const VIAL_INFO: (VialInfo | null)[] = [
  { name: "COPPER_CORONA", mainItem: "Copper", liquid: "Liquid1" },
  { name: "SIPPY_SPLINTERS", mainItem: "OakTree", liquid: "Liquid1" },
  { name: "MUSHROOM_SOUP", mainItem: "Grasslands1", liquid: "Liquid1" },
  { name: "SPOOL_SPRITE", mainItem: "CraftMat1", liquid: "Liquid1" },
  { name: "BARIUM_MIXTURE", mainItem: "CopperBar", liquid: "Liquid1" },
  { name: "DIETER_DRINK", mainItem: "Grasslands3", liquid: "Liquid1" },
  { name: "SKINNY_0_CAL", mainItem: "Jungle2", liquid: "Liquid1" },
  { name: "THUMB_POW", mainItem: "CraftMat5", liquid: "Liquid1" },
  { name: "JUNGLE_JUICE", mainItem: "JungleTree", liquid: "Liquid1" },
  { name: "BARLEY_BREW", mainItem: "IronBar", liquid: "Liquid1" },
  { name: "ANEARFUL", mainItem: "Forest1", liquid: "Liquid1" },
  { name: "TEA_WITH_PEA", mainItem: "ToiletTree", liquid: "Liquid1" },
  { name: "GOLD_GUZZLE", mainItem: "Gold", liquid: "Liquid1" },
  { name: "RAMIFICOCTION", mainItem: "Forest3", liquid: "Liquid1" },
  { name: "SEAWATER", mainItem: "Fish1", liquid: "Liquid1" },
  { name: "TAIL_TIME", mainItem: "Sewers2", liquid: "Liquid1" },
  { name: "FLY_IN_MY_DRINK", mainItem: "Bug1", liquid: "Liquid1" },
  { name: "MIMICRAUGHT", mainItem: "DesertA2", liquid: "Liquid1" },
  { name: "BLUE_FLAV", mainItem: "Plat", liquid: "Liquid1" },
  { name: "SLUG_SLURP", mainItem: "Fish2", liquid: "Liquid1" },
  { name: "PICKLE_JAR", mainItem: "BobJoePickle", liquid: "Liquid2" },
  { name: "FUR_REFRESHER", mainItem: "SnowA1", liquid: "Liquid2" },
  { name: "SIPPY_SOUL", mainItem: "Soul1", liquid: "Liquid2" },
  { name: "CRAB_JUICE", mainItem: "Critter2", liquid: "Liquid2" },
  { name: "VOID_VIAL", mainItem: "Void", liquid: "Liquid2" },
  { name: "RED_MALT", mainItem: "Refinery1", liquid: "Liquid2" },
  { name: "EW_GROSS_GROSS", mainItem: "Bug5", liquid: "Liquid2" },
  { name: "THE_SPANISH_SAHARA", mainItem: "SaharanFoal", liquid: "Liquid2" },
  { name: "POISON_TINCTURE", mainItem: "Critter1A", liquid: "Liquid2" },
  { name: "ETRUSCAN_LAGER", mainItem: "SnowB2", liquid: "Liquid2" },
  { name: "CHONKER_CHUG", mainItem: "Soul2", liquid: "Liquid2" },
  { name: "BUBONIC_BURP", mainItem: "Critter4", liquid: "Liquid3" },
  { name: "VISIBLE_INK", mainItem: "SnowB3", liquid: "Liquid3" },
  { name: "ORANGE_MALT", mainItem: "Refinery2", liquid: "Liquid3" },
  { name: "SNOW_SLURRY", mainItem: "SnowB5", liquid: "Liquid3" },
  { name: "SLOWERGY_DRINK", mainItem: "Soul4", liquid: "Liquid3" },
  { name: "SIPPY_CUP", mainItem: "SnowC1", liquid: "Liquid3" },
  { name: "BUNNY_BREW", mainItem: "Critter7", liquid: "Liquid3" },
  { name: "40-40_PURITY", mainItem: "SnowC4", liquid: "Liquid3" },
  { name: "SHAVED_ICE", mainItem: "Refinery5", liquid: "Liquid3" },
  { name: "GOOSEY_GLUG", mainItem: "Critter9", liquid: "Liquid3" },
  { name: "BALL_PICKLE_JAR", mainItem: "BallJoePickle", liquid: "Liquid1" },
  { name: "CAPACHINO", mainItem: "GalaxyA1", liquid: "Liquid3" },
  { name: "DONUT_DRINK", mainItem: "GalaxyA3", liquid: "Liquid3" },
  { name: "LONG_ISLAND_TEA", mainItem: "Fish6", liquid: "Liquid3" },
  { name: "SPOOK_PINT", mainItem: "Soul5", liquid: "Liquid3" },
  { name: "CALCIUM_CARBONATE", mainItem: "GalaxyB3", liquid: "Liquid3" },
  { name: "BLOAT_DRAFT", mainItem: "Critter10", liquid: "Liquid3" },
  { name: "CHOCO_MILKSHAKE", mainItem: "GalaxyB4", liquid: "Liquid3" },
  { name: "PEARL_SELTZER", mainItem: "GalaxyC1b", liquid: "Liquid3" },
  { name: "KRAKENADE", mainItem: "Fish8", liquid: "Liquid3" },
  { name: "ELECTROLYTE", mainItem: "GalaxyC4", liquid: "Liquid3" },
  { name: "ASH_AGUA", mainItem: "LavaA1", liquid: "Liquid3" },
  { name: "MAPLE_SYRUP", mainItem: "Tree9", liquid: "Liquid3" },
  { name: "HAMPTER_DRIPPY", mainItem: "LavaA5b", liquid: "Liquid3" },
  { name: "DREADNOG", mainItem: "DreadloBar", liquid: "Liquid3" },
  { name: "DUSTED_DRINK", mainItem: "Bug10", liquid: "Liquid3" },
  { name: "OJ_JOOCE", mainItem: "LavaB3", liquid: "Liquid3" },
  { name: "OOZIE_OOBLEK", mainItem: "Soul6", liquid: "Liquid3" },
  { name: "VENISON_MALT", mainItem: "LavaC2", liquid: "Liquid3" },
  { name: "MARBLE_MOCHA", mainItem: "Marble", liquid: "Liquid3" },
  { name: "WILLOW_SIPPY", mainItem: "Tree11", liquid: "Liquid3" },
  { name: "SHINYFIN_STEW", mainItem: "Fish13", liquid: "Liquid3" },
  { name: "DREAMY_DRINK", mainItem: "Bug11", liquid: "Liquid3" },
  { name: "RICECAKORADE", mainItem: "SpiA2", liquid: "Liquid4" },
  { name: "LADYBUG_SERUM", mainItem: "Bug12", liquid: "Liquid4" },
  { name: "FLAVORGIL", mainItem: "Fish12", liquid: "Liquid4" },
  { name: "GREENLEAF_TEA", mainItem: "SpiB1", liquid: "Liquid4" },
  { name: "FIREFLY_GROG", mainItem: "Bug13", liquid: "Liquid4" },
  { name: "DABAR_SPECIAL", mainItem: "GodshardBar", liquid: "Liquid4" },
  { name: "REFRESHMENT", mainItem: "Soul7", liquid: "Liquid4" },
  { name: "GIBBED_DRINK", mainItem: "SpiC2", liquid: "Liquid4" },
  { name: "DED_SAP", mainItem: "Tree13", liquid: "Liquid4" },
  { name: "ROYALE_COLA", mainItem: "SpiD3", liquid: "Liquid4" },
  { name: "TURTLE_TISANE", mainItem: "Critter11", liquid: "Liquid4" },
  { name: "CHAPTER_CHUG", mainItem: "Spelunking0", liquid: "Liquid4" },
  { name: "SIPPY_SEAWEED", mainItem: "Tree14", liquid: "Liquid4" },
  { name: "WRIGGLE_WATER", mainItem: "w7A3", liquid: "Liquid4" },
  { name: "ROCKY_BOBA", mainItem: "Prehistrium", liquid: "Liquid4" },
  { name: "OCTOSODA", mainItem: "Soul8", liquid: "Liquid4" },
  { name: "PAPER_PINT", mainItem: "Spelunking2", liquid: "Liquid4" },
  { name: "SCALE_ON_ICE", mainItem: "w7A5", liquid: "Liquid4" },
  { name: "TRASH_DRANK", mainItem: "Bug15", liquid: "Liquid4" },
  { name: "CRABOMAYSE", mainItem: "w7A12", liquid: "Liquid4" },
  { name: "SHIPINABOTTLE", mainItem: "w7B12b", liquid: "Liquid4" },
  { name: "CANTEEN_READ", mainItem: "Spelunking5", liquid: "Liquid4" }
];

export const VIAL_COSTS = [0, 100, 1e3, 2500, 1e4, 5e4, 1e5, 5e5, 1000001, 5e6, 25e6, 1e8, 1e9, 5e10];
export const MAX_VIAL_LEVEL = 13;

export const MEAL_INFO: NamedRaw[] = [
  { name: "Turkey_of_Thank", rawName: "CookingMB0" },
  { name: "Egg", rawName: "CookingMB1" },
  { name: "Salad", rawName: "CookingMB2" },
  { name: "Pie", rawName: "CookingMB3" },
  { name: "Frenk_Fries", rawName: "CookingMB4" },
  { name: "Spaghetti", rawName: "CookingMB5" },
  { name: "Corn", rawName: "CookingMB6" },
  { name: "Garlic_Bread", rawName: "CookingMB7" },
  { name: "Garlicles_Bread", rawName: "CookingMB8" },
  { name: "Pizza", rawName: "CookingMB9" },
  { name: "Apple", rawName: "CookingMB10" },
  { name: "Pancakes", rawName: "CookingMB11" },
  { name: "Corndog", rawName: "CookingMB12" },
  { name: "Cabbage", rawName: "CookingMB13" },
  { name: "Potato_P_Pastry", rawName: "CookingMB14" },
  { name: "Dango", rawName: "CookingMB15" },
  { name: "Sourish_Fish", rawName: "CookingMB16" },
  { name: "Octoplop", rawName: "CookingMB17" },
  { name: "Croissant", rawName: "CookingMB18" },
  { name: "Canopy", rawName: "CookingMB19" },
  { name: "Cannoli", rawName: "CookingMB20" },
  { name: "Cheese", rawName: "CookingMB21" },
  { name: "Sawdust", rawName: "CookingMB22" },
  { name: "Eggplant", rawName: "CookingMB23" },
  { name: "Cheesy_Bread", rawName: "CookingMB24" },
  { name: "Wild_Boar", rawName: "CookingMB25" },
  { name: "Donut", rawName: "CookingMB26" },
  { name: "Riceball", rawName: "CookingMB27" },
  { name: "Cauliflower", rawName: "CookingMB28" },
  { name: "Durian_Fruit", rawName: "CookingMB29" },
  { name: "Orange", rawName: "CookingMB30" },
  { name: "Bunt_Cake", rawName: "CookingMB31" },
  { name: "Chocala_Truffle", rawName: "CookingMB32" },
  { name: "Leek", rawName: "CookingMB33" },
  { name: "Fortune_Cookie", rawName: "CookingMB34" },
  { name: "Pretzel", rawName: "CookingMB35" },
  { name: "Sea_Urchin", rawName: "CookingMB36" },
  { name: "Mashed_Potato", rawName: "CookingMB37" },
  { name: "Mutton", rawName: "CookingMB38" },
  { name: "Wedding_Cake", rawName: "CookingMB39" },
  { name: "Eel", rawName: "CookingMB40" },
  { name: "Whipped_Cocoa", rawName: "CookingMB41" },
  { name: "Onion", rawName: "CookingMB42" },
  { name: "Soda", rawName: "CookingMB43" },
  { name: "Sushi_Roll", rawName: "CookingMB44" },
  { name: "Buncha_Banana", rawName: "CookingMB45" },
  { name: "Pumpkin", rawName: "CookingMB46" },
  { name: "Cotton_Candy", rawName: "CookingMB47" },
  { name: "Massive_Fig", rawName: "CookingMB48" },
  { name: "Chef_Geustloaf", rawName: "CookingMB49" },
  { name: "Kiwi_Fruit", rawName: "CookingMB50" },
  { name: "Popped_Corn", rawName: "CookingMB51" },
  { name: "Double_Cherry", rawName: "CookingMB52" },
  { name: "Ratatouey", rawName: "CookingMB53" },
  { name: "Giant_Tomato", rawName: "CookingMB54" },
  { name: "Wrath_Grapes", rawName: "CookingMB55" },
  { name: "Sausy_Sausage", rawName: "CookingMB56" },
  { name: "Seasoned_Marrow", rawName: "CookingMB57" },
  { name: "Sticky_Bun", rawName: "CookingMB58" },
  { name: "Frazzleberry", rawName: "CookingMB59" },
  { name: "MrLoin_Steak", rawName: "CookingMB60" },
  { name: "Large_Pohayoh", rawName: "CookingMB61" },
  { name: "Bill_Jack_Pep", rawName: "CookingMB62" },
  { name: "Burned_Mello", rawName: "CookingMB63" },
  { name: "Yumi_Peachring", rawName: "CookingMB64" },
  { name: "Plumpcakes", rawName: "CookingMB65" },
  { name: "Nyanborgir", rawName: "CookingMB66" },
  { name: "Tempura_Shrimp", rawName: "CookingMB67" },
  { name: "Woahtermelon", rawName: "CookingMB68" },
  { name: "Cookies", rawName: "CookingMB69" },
  { name: "Singing_Seed", rawName: "CookingMB70" },
  { name: "Tasty_Treat", rawName: "CookingMB71" },
  { name: "Giga_Chip", rawName: "CookingMB72" },
  { name: "Divorce_Cake", rawName: "CookingMB73" }
];

export const PREMIUM_HATS: NamedRaw[] = [
  { rawName: "EquipmentHatsBeg1", name: "Ice_Cream_Sundae" },
  { rawName: "EquipmentHats10", name: "Pink_Headband" },
  { rawName: "EquipmentHats84", name: "The_Crow_Perch" },
  { rawName: "EquipmentHats21", name: "Birthday_Hat" },
  { rawName: "EquipmentHats24", name: "Farmer_Brimest" },
  { rawName: "EquipmentHats107", name: "Shiny_Bored_Beanie" },
  { rawName: "EquipmentHats42", name: "Santa_Hat" },
  { rawName: "EquipmentHats111", name: "Epic_Santa_Hat" },
  { rawName: "EquipmentHats51", name: "Big_Pretty_Bow" },
  { rawName: "EquipmentHats55", name: "Steam_Cap" },
  { rawName: "EquipmentHats108", name: "3rd_Anniversary_Ice_Cream_Topper" },
  { rawName: "EquipmentHats56", name: "Bunny_Ears" },
  { rawName: "EquipmentHats63", name: "Summer_Shell" },
  { rawName: "EquipmentHats64", name: "Nuget_Cake_Fedora" },
  { rawName: "EquipmentHats66", name: "Honker_Hat" },
  { rawName: "EquipmentHats67", name: "Acorn_Topper" },
  { rawName: "EquipmentHats75", name: "Apple_Launch_Hat" },
  { rawName: "EquipmentHats76", name: "Funny_Hat" },
  { rawName: "EquipmentHats78", name: "Meteorhead" },
  { rawName: "EquipmentHats79", name: "Ice_Guard_Helmet" },
  { rawName: "EquipmentHats31", name: "Smitty's_Bubble_Blowing_Hat" },
  { rawName: "EquipmentHats32", name: "Bandit_Bob_Mask" },
  { rawName: "EquipmentHats33", name: "Paper_Bag" },
  { rawName: "EquipmentHats34", name: "Parasite" },
  { rawName: "EquipmentHats35", name: "Diamond_Horns" },
  { rawName: "EquipmentHats36", name: "Halloween_Pumpkin" },
  { rawName: "EquipmentHats40", name: "Pardoned_Turkey" },
  { rawName: "EquipmentHats37", name: "Hotdog_Hero" },
  { rawName: "EquipmentHats38", name: "Invisible_Hat" },
  { rawName: "EquipmentHats46", name: "Strawbiggy" },
  { rawName: "EquipmentHats47", name: "Pop_Cat" },
  { rawName: "EquipmentHats48", name: "Dairy_Dunk" },
  { rawName: "EquipmentHats49", name: "The_Classic" },
  { rawName: "EquipmentHats50", name: "Green_Beanie" },
  { rawName: "EquipmentHats43", name: "Snowman" },
  { rawName: "EquipmentHats45", name: "Giftmas_Tree" },
  { rawName: "EquipmentHats57", name: "Big_Bunny" },
  { rawName: "EquipmentHats62", name: "Fluffy_Ramsy" },
  { rawName: "EquipmentHats65", name: "The_Red_Boaty" },
  { rawName: "EquipmentHats69", name: "Giftmas_Snoozy_Cap" },
  { rawName: "EquipmentHats80", name: "Corgi_Topper" },
  { rawName: "EquipmentHats109", name: "Husky_Hat" },
  { rawName: "EquipmentHats81", name: "Siege_Captain_Cap" },
  { rawName: "EquipmentHats82", name: "Ele_Sorcerer_Pointed_Hat" },
  { rawName: "EquipmentHats85", name: "Bedsheet_with_Holes" },
  { rawName: "EquipmentHats86", name: "Carrotman_Mask" },
  { rawName: "EquipmentHats87", name: "Glublin_Mask" },
  { rawName: "EquipmentHats88", name: "Bloque_Mask" },
  { rawName: "EquipmentHats89", name: "Borzoi_Topper" },
  { rawName: "EquipmentHats90", name: "Straw_Hat" },
  { rawName: "EquipmentHats91", name: "Wig_Bandana" },
  { rawName: "EquipmentHats92", name: "Funky_Hat" },
  { rawName: "EquipmentHats93", name: "Reinforced_Headband" },
  { rawName: "EquipmentHats94", name: "Shogun_Helmet" },
  { rawName: "EquipmentHats95", name: "Gilded_Headband" },
  { rawName: "EquipmentHats96", name: "Bamboo_Hat" },
  { rawName: "EquipmentHats97", name: "Festive_Beast_Mask" },
  { rawName: "EquipmentHats98", name: "Heiress_Headdress" },
  { rawName: "EquipmentHats99", name: "Spirited_Mane" },
  { rawName: "EquipmentHats100", name: "Fiery_Mane" },
  { rawName: "EquipmentHats101", name: "Guardian_Mane" },
  { rawName: "EquipmentHats102", name: "Fanned_Blossomage" },
  { rawName: "EquipmentHats103", name: "Dainty_Brim" },
  { rawName: "EquipmentHats104", name: "Charcoal_Hat" },
  { rawName: "EquipmentHats110", name: "Yellow_Beanie" },
  { rawName: "EquipmentHats112", name: "Deathbringer_Hood_of_Death" },
  { rawName: "EquipmentHats113", name: "Pink_Beanie" },
  { rawName: "EquipmentHats114", name: "True_Crown" },
  { rawName: "EquipmentHats115", name: "Celebration_Mane" },
  { rawName: "EquipmentHats116", name: "Goldberry" },
  { rawName: "EquipmentHats117", name: "Orange_Beanie" },
  { rawName: "EquipmentHats118", name: "Windwalker_Hood" },
  { rawName: "EquipmentHats120", name: "Umbrella_Brim" },
  { rawName: "EquipmentHats121", name: "Bloo_Creamer" },
  { rawName: "EquipmentHats122", name: "Arcanist_Crown" },
  { rawName: "EquipmentHats124", name: "Alpine_Beanie" },
  { rawName: "EquipmentHats125", name: "Rudolph_Antlers" },
  { rawName: "EquipmentHats126", name: "Helper_Elf_Hat" },
  { rawName: "EquipmentHats127", name: "Seal_Team_Skipper_Hat" },
  { rawName: "EquipmentHats128", name: "Lovely_Top_Hat" },
  { rawName: "EquipmentHats129", name: "Polkadot_Beanie" },
  { rawName: "EquipmentHats130", name: "Leprechaun_Hat" },
  { rawName: "EquipmentHats131", name: "Lucky_Ducky_Brim" },
  { rawName: "EquipmentHats132", name: "Time_Traveler_Top_Hat" },
  { rawName: "EquipmentHats133", name: "Native_Headdress" },
  { rawName: "EquipmentHats134", name: "Starry_Hairpins" },
  { rawName: "EquipmentHats135", name: "Blonde_Hairpiece" },
  { rawName: "EquipmentHats139", name: "Sun_Hat" }
];

export const TROPHIES: NamedRaw[] = [
  { rawName: "Trophy1", name: "King_of_Food" },
  { rawName: "Trophy2", name: "Lucky_Lad" },
  { rawName: "Trophy3", name: "Club_Member" },
  { rawName: "Trophy4", name: "I_Made_This_Game" },
  { rawName: "Trophy5", name: "Dice_Dynamo" },
  { rawName: "Trophy6", name: "Blunder_Hero" },
  { rawName: "Trophy7", name: "Original_Gamer" },
  { rawName: "Trophy8", name: "Trailblazer" },
  { rawName: "Trophy9", name: "Ultra_Unboxer" },
  { rawName: "Trophy10", name: "Critter_Baron" },
  { rawName: "Trophy11", name: "YumYum_Sheriff" },
  { rawName: "Trophy12", name: "Megalodon" },
  { rawName: "Trophy13", name: "Club_Maestro" },
  { rawName: "Trophy14", name: "Beach_Bro" },
  { rawName: "Trophy15", name: "Frost_Prince" },
  { rawName: "Trophy16", name: "Idle_Skiller" },
  { rawName: "Trophy17", name: "One_of_the_Divine" },
  { rawName: "Trophy18", name: "Master_of_Nothing" },
  { rawName: "Trophy19", name: "Nebula_Royal" },
  { rawName: "Trophy20", name: "Luckier_Lad" },
  { rawName: "Trophy21", name: "Baller" },
  { rawName: "Trophy22", name: "Gladiator" },
  { rawName: "Trophy23", name: "Heroic_Spirit" },
  { rawName: "Trophy24", name: "Nine_Dart_Finish" },
  { rawName: "Trophy25", name: "Luckiest_Lad" }
];

export const NAMETAGS: NamedRaw[] = [
  { rawName: "EquipmentNametag1", name: "Riftwalker_Nametag" },
  { rawName: "EquipmentNametag2", name: "Lava's_Awesome_Nametag" },
  { rawName: "EquipmentNametag3", name: "Balling_Nametag" },
  { rawName: "EquipmentNametag4", name: "Vman_Nametag" },
  { rawName: "EquipmentNametag5", name: "Spring_Flowers_Nametag" },
  { rawName: "EquipmentNametag6b", name: "Trash_Tuna_Nametag" },
  { rawName: "EquipmentNametag7", name: "Island_Adventurer_Nametag" },
  { rawName: "EquipmentNametag8", name: "Summer_Shovel_Nametag" },
  { rawName: "EquipmentNametag9", name: "Falloween_Nametag" },
  { rawName: "EquipmentNametag10", name: "3rd_Anniversary_IdleOn_Nametag" },
  { rawName: "EquipmentNametag11", name: "Nightshade_Nametag" },
  { rawName: "EquipmentNametag12", name: "Megafeather_Nametag" },
  { rawName: "EquipmentNametag13", name: "Timeless_Nametag" },
  { rawName: "EquipmentNametag14", name: "Snowflake_Nametag" },
  { rawName: "EquipmentNametag15", name: "Frostyman_Nametag" },
  { rawName: "EquipmentNametag16", name: "Lovely_Day_Nametag" },
  { rawName: "EquipmentNametag17", name: "Spectacular_4th_Year_Nametag" },
  { rawName: "EquipmentNametag18", name: "4th_Anniversary_IdleOn_Nametag" },
  { rawName: "EquipmentNametag19", name: "Aethermoon_Nametag" },
  { rawName: "EquipmentNametag20", name: "Deadbones_Nametag" },
  { rawName: "EquipmentNametag21", name: "Treasure_Nametag" },
  { rawName: "EquipmentNametag22", name: "Tome_Apprentice_Nametag" },
  { rawName: "EquipmentNametag23", name: "Tome_Journeyman_Nametag" },
  { rawName: "EquipmentNametag24", name: "Tome_Expert_Nametag" },
  { rawName: "EquipmentNametag25", name: "Tome_Elite_Nametag" },
  { rawName: "EquipmentNametag26", name: "Tome_Pro_Nametag" },
  { rawName: "EquipmentNametag27", name: "Tome_Master_Nametag" },
  { rawName: "EquipmentNametag28", name: "Tome_Legend_Nametag" },
  { rawName: "EquipmentNametag29", name: "Reliquarium_Nametag" },
  { rawName: "EquipmentNametag30", name: "Cropfall_Nametag" },
  { rawName: "EquipmentNametag31", name: "Gingerbread_Nametag" },
  { rawName: "EquipmentNametag32", name: "Sweet_Chocolate_Nametag" },
  { rawName: "EquipmentNametag33", name: "Pot_of_Gold_Nametag" },
  { rawName: "EquipmentNametag34", name: "Emerald_Nametag" },
  { rawName: "EquipmentNametag35", name: "5th_Anniversary_IdleOn_Nametag" },
  { rawName: "EquipmentNametag36", name: "Wonderful_5th_Year_Nametag" },
  { rawName: "EquipmentNametag37", name: "Grand_Egg_Nametag" },
  { rawName: "EquipmentNametag41", name: "All_That_Glitters_Nametag" }
];

export const TOWER_BONUS_INC: number[] = [1, 1.18, 1.23, 2, 1.27, 1.106, 1.95, 4, 1.14, 1.365, 1.33, 1.276, 1.246, 1.23, 1.222, 1.22, 1.21, 1.4, 1.16, 1.15, 1.13, 1.115, 1.11, 1.106, 1.106, 1.1, 1.09];
export const BUILD_COST_MULTIPLIER: number[] = [3, 200, 2250, 12000, 25000, 60000, 100000, 150000, 50000000, 5, 100, 700, 5000, 40000, 125000, 400000, 1000000, 3500000, 10, 250, 1000, 7500, 40000, 200000, 2000000, 7000000, 60000000];
export const REFINERY_POWER_CAPS: number[] = [50, 50, 200, 800, 3000, 8000, 14000, 20000, 30000, 40000, 50000, 65000, 80000, 100000, 200000, 300000, 400000, 500000, 600000, 700000, 800000, 900000, 1000000, 1000000, 1000000, 1000000];

export const REFINERY_SALT_INFO: RefinerySaltInfo[] = [
  { rawName: "Refinery1", saltName: "Redox_Salts", cost: [{ rawName: "Grasslands1", quantity: 10 }, { rawName: "Copper", quantity: 5 }] },
  { rawName: "Refinery2", saltName: "Explosive_Salts", cost: [{ rawName: "Forest3", quantity: 10 }, { rawName: "ForestTree", quantity: 5 }, { rawName: "Refinery1", quantity: 2 }] },
  { rawName: "Refinery3", saltName: "Spontaneity_Salts", cost: [{ rawName: "DesertA1", quantity: 50 }, { rawName: "Fish1", quantity: 30 }, { rawName: "Bug1", quantity: 40 }, { rawName: "Refinery2", quantity: 2 }] },
  { rawName: "Refinery4", saltName: "Dioxide_Synthesis", cost: [{ rawName: "SnowA1", quantity: 10 }, { rawName: "Soul2", quantity: 2 }, { rawName: "Critter3", quantity: 1 }, { rawName: "Refinery3", quantity: 1 }] },
  { rawName: "Refinery5", saltName: "Purple_Salt", cost: [{ rawName: "SnowB4", quantity: 25 }, { rawName: "Fish4", quantity: 5 }, { rawName: "Bug3", quantity: 5 }, { rawName: "Critter4", quantity: 5 }, { rawName: "Refinery4", quantity: 2 }] },
  { rawName: "Refinery6", saltName: "Nullo_Salt", cost: [{ rawName: "SnowC4", quantity: 50 }, { rawName: "VoidBar", quantity: 5 }, { rawName: "Tree7", quantity: 5 }, { rawName: "Bug6", quantity: 5 }, { rawName: "Soul4", quantity: 5 }, { rawName: "Refinery5", quantity: 2 }] },
  { rawName: "Refinery7", saltName: "Crosslink_Salt", cost: [{ rawName: "SpiB2", quantity: 10 }, { rawName: "Soul7", quantity: 2 }, { rawName: "Critter11", quantity: 1 }, { rawName: "Refinery6", quantity: 1 }] },
  { rawName: "Refinery8", saltName: "Propagated_Salt", cost: [{ rawName: "w7A1", quantity: 25 }, { rawName: "Fish12", quantity: 5 }, { rawName: "Bug15", quantity: 5 }, { rawName: "PrehistriumBar", quantity: 5 }, { rawName: "Refinery7", quantity: 2 }] },
  { rawName: "Refinery9", saltName: "Anionic_Salt", cost: [{ rawName: "w7B10", quantity: 50 }, { rawName: "FillerMaterial", quantity: 5 }, { rawName: "FillerMaterial", quantity: 5 }, { rawName: "FillerMaterial", quantity: 5 }, { rawName: "Soul8", quantity: 5 }, { rawName: "Refinery8", quantity: 2 }] }
];

export const SIGIL_INFO: SigilInfo[] = [
  { name: "BIG_MUSCLE", boostCost: 100, jadeCost: 50000, etherealCost: 250000, eclecticCost: 10000000 },
  { name: "PUMPED_KICKS", boostCost: 150, jadeCost: 60000, etherealCost: 300000, eclecticCost: 20000000 },
  { name: "ODD_LITEARTURE", boostCost: 200, jadeCost: 70000, etherealCost: 400000, eclecticCost: 30000000 },
  { name: "GOOD_FORTUNE", boostCost: 300, jadeCost: 90000, etherealCost: 500000, eclecticCost: 50000000 },
  { name: "PLUNGING_SWORD", boostCost: 700, jadeCost: 100000, etherealCost: 600000, eclecticCost: 60000000 },
  { name: "WIZARDLY_HAT", boostCost: 1250, jadeCost: 130000, etherealCost: 700000, eclecticCost: 100000000 },
  { name: "ENVELOPE_PILE", boostCost: 2500, jadeCost: 160000, etherealCost: 1000000, eclecticCost: 250000000 },
  { name: "SHINY_BEACON", boostCost: 4000, jadeCost: 200000, etherealCost: 1400000, eclecticCost: 70000000 },
  { name: "METAL_EXTERIOR", boostCost: 7000, jadeCost: 240000, etherealCost: 1700000, eclecticCost: 200000000 },
  { name: "TWO_STARZ", boostCost: 10000, jadeCost: 280000, etherealCost: 2200000, eclecticCost: 300000000 },
  { name: "PIPE_GAUGE", boostCost: 12000, jadeCost: 320000, etherealCost: 2600000, eclecticCost: 600000000 },
  { name: "TROVE", boostCost: 14000, jadeCost: 400000, etherealCost: 3000000, eclecticCost: 1250000000 },
  { name: "PEA_POD", boostCost: 15000, jadeCost: 420000, etherealCost: 3500000, eclecticCost: 2500000000 },
  { name: "TUFT_OF_HAIR", boostCost: 25000, jadeCost: 450000, etherealCost: 4300000, eclecticCost: 6000000000 },
  { name: "EMOJI_VEGGIE", boostCost: 33000, jadeCost: 480000, etherealCost: 5500000, eclecticCost: 12000000000 },
  { name: "VIP_PARCHMENT", boostCost: 42000, jadeCost: 520000, etherealCost: 6700000, eclecticCost: 25000000000 },
  { name: "DREAM_CATCHER", boostCost: 50000, jadeCost: 560000, etherealCost: 8200000, eclecticCost: 40000000000 },
  { name: "DUSTER_STUDS", boostCost: 60000, jadeCost: 600000, etherealCost: 10000000, eclecticCost: 60000000000 },
  { name: "GARLIC_GLOVE", boostCost: 70000, jadeCost: 650000, etherealCost: 12000000, eclecticCost: 100000000000 },
  { name: "LAB_TESSTUBE", boostCost: 80000, jadeCost: 700000, etherealCost: 14000000, eclecticCost: 200000000000 },
  { name: "PECULIAR_VIAL", boostCost: 120000, jadeCost: 750000, etherealCost: 15000000, eclecticCost: 350000000000 },
  { name: "LOOT_PILE", boostCost: 160000, jadeCost: 900000, etherealCost: 16000000, eclecticCost: 500000000000 },
  { name: "DIV_SPIRAL", boostCost: 200000, jadeCost: 1200000, etherealCost: 17000000, eclecticCost: 700000000000 },
  { name: "COOL_COIN", boostCost: 250000, jadeCost: 2000000, etherealCost: 20000000, eclecticCost: 1000000000000 }
];

export const POPPY_UPGRADES: PoppyUpgrade[] = [
  { name: "tasty_Fishbait", x1: 4, x2: 1.06, x3: 100 },
  { name: "Quick_Reeling", x1: 150, x2: 1.2, x3: 500 },
  { name: "Shiny_Lure", x1: 500, x2: 3.5, x3: 2500 },
  { name: "Bonuses_from_Poppy", x1: 10000, x2: 3, x3: 30000 },
  { name: "fishy_discount", x1: 30000, x2: 1.13, x3: 250000 },
  { name: "Juicy_Worm", x1: 150000, x2: 1.07, x3: 3000000 },
  { name: "Fisheroo_Reset", x1: 40000000, x2: 20, x3: 25000000 },
  { name: "Fishing_Buddy", x1: 1200000000, x2: 7.5, x3: 600000000 },
  { name: "Lightning_Quickness", x1: 600000000, x2: 1.12, x3: 4000000000 },
  { name: "Fisheroo_Investing", x1: 7500000000, x2: 1.7, x3: 14000000000 },
  { name: "Multihook_Fishing", x1: 20000000000, x2: 1.12, x3: 80000000000 },
  { name: "Greatest_Catch", x1: 1500000000000, x2: 15, x3: 400000000000 }
];

export const VILLAGER_NAMES = ['Explorer', 'Engineer', 'Bonuses', 'Measure', 'Studies'] as const;
export const STUDY_NAMES = ["THE_WELL", "MOTHERLODE", "THE_DEN", "BRAVERY", "THE_BELL", "THE_HARP", "THE_LAMP", "THE_HIVE", "GROTTO", "JUSTICE", "THE_JARS", "EVERTREE", "WISDOM", "GAMBIT", "TEMPLE", "FOUNTAIN", "TRENCH", "THE_COVE", "BRUH", "BRUH"] as const;

export const DEFAULT_MEAL_MAX_LEVEL = 110;

export const ARCADE_EFFECTS = [
  "+{_Base_Damage",
  "+{_Base_Defence",
  "+{%_Total_Accuracy",
  "+{%_Mining_EXP_gain",
  "+{%_Fishing_EXP_gain",
  "+{%_Sample_Size",
  "+{%_AFK_Gains_Rate",
  "+{_Cap_for_all_Liquids",
  "+{%_Multikill_per_Tier",
  "+{%_Catching_EXP_gain",
  "+{%_Cash_from_Mobs",
  "+{%_Cash_from_Mobs",
  "+{%_Class_EXP_gain",
  "+{%_Shiny_Chance",
  "+{%_Trapping_EXP",
  "+{_Starting_TD_Pts",
  "+{_Tab_1_Talent_Pt",
  "+{_Weapon_Power",
  "+{%_Skill_EXP_gain",
  "+{_Base_STR",
  "+{_Base_AGI",
  "+{_Base_WIS",
  "+{_Base_LUK",
  "+{%_Trapping_Critters",
  "+{%_Worship_Souls",
  "+{%_Refinery_Speed",
  "+{%_Forge_Capacity",
  "+{%_Drop_Rate",
  "+{%_Cook_SPD_multi",
  "+{%_Lab_EXP_gain",
  "+{%_Breed_Mob_DMG",
  "+{%_Nugget_Regen",
  "+{%_Artifact_Find",
  "+{%_Sailing_Loot",
  "+{%_W_Ess_gain",
  "+{%_Jade_gain",
  "+{%_Farming_EXP",
  "+{%_Divinity_EXP",
  "+{%_Villager_XP_multi",
  "+{%_Gold_Ball_Gain",
  "+{%_Deathbringer_Bones",
  "+{%_Equinox_Fill_Rate",
  "+{%_Monument_AFK",
  "+{%_Sigil_Speed",
  "+{%_Construction_Build",
  "+{%_Burger",
  "+{%_Total_Damage",
  "+{%_Windwalker_Dust",
  "+{%_Medallion_Chance",
  "+{%_Breedability_Rate",
  "+{%_Arcane_Tachyons",
  "+{%_Emperor_Bonuses",
  "+{%_Sneaking_XP_multi",
  "+{%_Summon_XP_multi",
  "+{%_Prisma_Bonuses",
  "+{%_Spelunking_Amber",
  "+{%_Spelunk_XP_multi",
  "+{%_Daily_Coral",
  "+{%_Palette_Luck",
  "+{%_Meritocracy_Bonus",
  "+{%_Class_XP_multi",
  "+{%_Kruk_Bubble_LVs",
  "+{%_Minehead_Currency",
  "+{%_Research_XP",
  "+{%_Megacrop_Chance",
  "+{%_New_Crown_Chance",
  "+{%_Artifact_Find",
  "+{%_Sushi_Bucks",
  "+{%_Fountain_Speed",
  "+{%_Cook_Mastery_EXP"
];

/** Max spendable legend talent levels (x1). Fillers 40–49 are 0. */
export const LEGEND_TALENT_MAX = [
  2, 4, 3, 3, 2, 5, 2, 5, 2, 2, 5, 4, 3, 4, 1, 2, 2, 2, 2, 2, 4, 5, 1, 3, 1, 3, 2, 3, 2, 2, 2, 3, 1, 2, 2, 1, 5, 1, 1, 1
];

export const LEGEND_COG_TALENT_INDEX = 18;
export const LEGEND_COG_TALENT_X2 = 2;
export const LEGEND_MASTERCLASS_TALENT_INDEX = 23;
export const LEGEND_MASTERCLASS_TALENT_X2 = 8;
export const JEWEL_COGS_SUPERBIT_INDEX = 33;
export const DOUBLE_CLUSTER_INDEX = 3;
export const DOUBLE_CLUSTER_X1 = 8;
export const DOUBLE_CLUSTER_X2 = 1.17;
export const DOUBLE_CLUSTER_MAX = 100;

export const RESEARCH_OCCURRENCE_NAMES = [
  "Bored_Tree",
  "Shopping_Oyseter",
  "Bridge_Plank",
  "Carrot_Patch",
  "Salty_Seawebs",
  "Dogbone_Tombstone",
  "Ominous_Signage",
  "Canyon_Pointerino",
  "Corange_Coral",
  "Oasis_Erosion",
  "Barnacle_Brothers",
  "Green_Shallowrock",
  "Broken_Spacerocks",
  "Meenie_Cactus",
  "Coraltree_Branch",
  "Useless_Anchor",
  "Oboe_Coral_Trio",
  "Spadespire",
  "Seaswept_Ruins",
  "Tetrino_Stones",
  "Stalagtite",
  "OG_Secret_Rock",
  "Happy_Piggy",
  "Treeception",
  "Keymaster",
  "Space_Drip",
  "Coralcave_Coral",
  "Unblinking_Eye",
  "Monster_Decoy",
  "Standard_Stump",
  "Big_Ol_Reef",
  "Oasis_Palm",
  "Stalagmite",
  "Rope_Lamp",
  "Unremarkable_Rock",
  "Standard_Mine",
  "Ancient_Chainrope",
  "Birchtree_Bitty",
  "Unreachable_Grate",
  "Genuine_Deadwood",
  "Rifty_Crystals",
  "Pirate_Flag",
  "Happy_Tree"
];

export const SUSHI_NAMES = [
  "Fish_Eggs",
  "Eggroll",
  "Egg_Maki",
  "Sashimi",
  "Tuna_Maki",
  "Salmon_Uramaki",
  "Salmon_Maki",
  "Cucumber_Uramaki",
  "Cucumber_Maki",
  "Onigiri",
  "Toro_Slice",
  "Toro_Nigiri",
  "Beef_Nigiri",
  "Beef_Tobo_Nigiri",
  "Tobiko_Maki",
  "Tobiko_Temaki",
  "Tobiko_Cluster",
  "Tobo_Sardine",
  "Tobo_Twins",
  "Live_Squid",
  "Live_Octopus",
  "Calamari_Ring",
  "Bluefin_Ring",
  "Tobo_Tamago",
  "Tako_Sashimi",
  "Hamachi_Sashimi",
  "Fat_Tuna_Sashimi",
  "King_Beef_Sashimi",
  "Salmon_Sashimi",
  "Salmon_Nigiri",
  "Fried_Bass_Nigiri",
  "Seasoned_Bass_Nigiri",
  "Jumbo_Shrimp",
  "Aged_Shrimp_Nigiri",
  "Tempura_Shrimp",
  "Ika_Sashimi",
  "Abalone_Sashimi",
  "Aji_Sashimi",
  "Aji_Aji_Sashimi",
  "Bubba_Grand_Salmon",
  "Tobiko_Roll",
  "Spicy_Tuna_Roll",
  "Salmon_Uramajor",
  "Sesame_Salmon_Muramajor",
  "Dragon_Roll",
  "Imaginei_Dragonroll",
  "Dragon_Nigiri",
  "Tamago_Nigiri",
  "Unagi_Nigiri",
  "Soylent_Nigiri",
  "Masago",
  "Masago_Temaki",
  "Masagoroll",
  "Caviar_Supreme",
  "Dulce_Vitiri",
  "Wasabaisamarama",
  "Kraken_Roll",
  "Leviathan_Roll",
  "Golthulu_Roll"
];
export type LabMatReq = { name?: string; rawName: string; amount: number };
export type LabItemInfo = { name: string; rawName: string; req: LabMatReq[] };
export type ButtonTaskInfo = { description: string; base: number; scaling: 'linear' | 'step' | 'exponent'; factor: number };

export const PET_RAW_NAMES: string[][] = [["mushG","frogG","beanG","poopSmall","ratB","slimeG","snakeG","carrotO","branch","acorn","goblinG","plank","frogBIG","mushR","mushW"],["jarSand","mimicA","crabcake","shovelR","coconut","sandcastle","pincermin","potato","steak","moonman","sandgiant","snailZ"],["bloque","flake","speaker","penguin","eye","mamoth","snakeB","glass","stache","snowball","thermostat","sheep","ram"],["mushP","w4a2","w4a3","demonP","w4b2","w4b1","w4b3","w4b4","w4b5","w4c1","w4c2","w4c3","w4c4"]];

export const BUTTON_PERM = [42,89,15,63,28,91,3,76,54,11,68,24,95,37,80,1,59,22,73,14,66,9,83,31,47,70,5,98,26,61,18,85,34,72,0,56,13,92,40,77,21,64,8,99,30,52,17,69,2,88,45,12,79,33,94,6,57,25,81,39,67,4,90,53,19,74,29,87,10,62,36,96,23,58,41,78,16,65,32,84,27,7,71,44,93,20,60,35,82,48,97,38,75,50,86,43,55,49,46,51];

export const BUTTON_TASKS: ButtonTaskInfo[] = [
  { description: "Have_a_total_of_{_STR_or_more", base: 1000, scaling: "exponent", factor: 1.045 },
  { description: "Have_a_total_of_{_AGI_or_more", base: 1000, scaling: "exponent", factor: 1.045 },
  { description: "Have_a_total_of_{_WIS_or_more", base: 1000, scaling: "exponent", factor: 1.045 },
  { description: "Have_a_total_of_{_LUK_or_more", base: 400, scaling: "exponent", factor: 1.04 },
  { description: "Have_{_of_the_1st_type_of_Deathbringer_Bones_in_your_Grimoire", base: 5000, scaling: "exponent", factor: 1.18 },
  { description: "Have_{_of_the_2nd_type_of_Windwalker_Dust_in_your_Compass", base: 3000, scaling: "exponent", factor: 1.16 },
  { description: "Have_{_of_the_3rd_type_of_Arcane_Cultist_Tachyon_in_your_Tesseract", base: 1500, scaling: "exponent", factor: 1.14 },
  { description: "Have_{_of_the_4rd_type_of_Arcane_Cultist_Tachyon_in_your_Tesseract", base: 1000, scaling: "exponent", factor: 1.12 },
  { description: "Level_up_your_DRAGON_Statue_to_at_least_LV_{", base: 100, scaling: "linear", factor: 1.5 },
  { description: "Level_up_your_MINING_Statue_to_at_least_LV_{", base: 100, scaling: "linear", factor: 1.5 },
  { description: "Level_up_your_LUMBERBOB_Statue_to_at_least_LV_{", base: 100, scaling: "linear", factor: 1.5 },
  { description: "Level_up_your_OCEANMAN_Statue_to_at_least_LV_{", base: 100, scaling: "linear", factor: 1.5 },
  { description: "Level_up_your_OL_RELIABLE_Statue_to_at_least_LV_{", base: 100, scaling: "linear", factor: 1.5 },
  { description: "Level_up_your_BOX_Statue_to_at_least_LV_{", base: 100, scaling: "linear", factor: 1.5 },
  { description: "Level_up_your_TWOSOUL_Statue_to_at_least_LV_{", base: 100, scaling: "linear", factor: 1.5 },
  { description: "Have_a_{x_Class_EXP_multi_or_higher", base: 100, scaling: "exponent", factor: 1.15 },
  { description: "Have_a_{x_Drop_Rate_multi_or_higher", base: 25, scaling: "exponent", factor: 1.031 },
  { description: "Level_up_your_Crystallin_Stamp_to_at_least_LV_{", base: 25, scaling: "linear", factor: 1.6 },
  { description: "Level_up_your_Roid_Ragin_Bubble_to_at_least_LV_{", base: 200, scaling: "exponent", factor: 1.035 },
  { description: "Level_up_your_Swift_Steppin_Bubble_to_at_least_LV_{", base: 200, scaling: "exponent", factor: 1.035 },
  { description: "Level_up_your_Stable_Jenius_Bubble_to_at_least_LV_{", base: 200, scaling: "exponent", factor: 1.035 },
  { description: "Have_a_Construction_Build_Rate_of_at_least_{/hr", base: 50000000, scaling: "exponent", factor: 1.13 },
  { description: "Have_a_3d_Printer_sample_of_Copper_Ore_of_at_least_{/hr", base: 100000, scaling: "exponent", factor: 1.15 },
  { description: "Save_up_{_Feathers_for_your_pal_Orion", base: 1000000000, scaling: "exponent", factor: 1.5 },
  { description: "Have_a_total_of_{_Waves,_according_to_your_Miniature_Soul_Apparatus", base: 500, scaling: "linear", factor: 3.5 },
  { description: "Have_a_Breeding_Mob_with_at_least_{_power_in_your_1st_storage_slot", base: 25000, scaling: "exponent", factor: 1.023 },
  { description: "Have_a_Foraging_Speed_of_at_least_{_in_the_Desert_Oasis_Breeding_grounds", base: 100000, scaling: "exponent", factor: 1.047 },
  { description: "Put_a_Tier_{_or_better_Ribbon_on_Yumi_Peachring_in_Cooking", base: 5, scaling: "step", factor: 20 },
  { description: "Level_up_your_Sausy_Sausage_meal_to_at_least_LV_{", base: 25, scaling: "step", factor: 2.5 },
  { description: "Have_a_Tome_Score_of_at_least_{_PTS", base: 5000, scaling: "exponent", factor: 1.011 },
  { description: "Reach_Laboratory_LV_{_or_higher", base: 100, scaling: "linear", factor: 3 },
  { description: "Reach_Sneaking_LV_{_or_higher", base: 200, scaling: "linear", factor: 4.3 },
  { description: "Reach_Spelunking_LV_{_or_higher", base: 25, scaling: "linear", factor: 1.3 },
  { description: "Reach_Mining_LV_{_or_higher", base: 75, scaling: "step", factor: 2 },
  { description: "Reach_Choppin_LV_{_or_higher", base: 75, scaling: "step", factor: 2 },
  { description: "Reach_Divinity_LV_{_or_higher", base: 100, scaling: "linear", factor: 2.5 },
  { description: "Save_up_{_Divinity_PTS", base: 1000000, scaling: "exponent", factor: 1.1 },
  { description: "Save_up_{_bars_of_gold_in_Sailing", base: 1000000, scaling: "exponent", factor: 1.13 },
  { description: "Have_a_total_Artifact_Find_Chance_multi_of_{x_or_higher_in_Sailing", base: 1000, scaling: "exponent", factor: 1.037 },
  { description: "Save_up_{_Gaming_Bits", base: 1000000000, scaling: "exponent", factor: 3 },
  { description: "Evolve_a_total_of_{_Plants_in_Gaming,_as_shown_by_your_Elegant_Seashell", base: 1000, scaling: "exponent", factor: 1.042 },
  { description: "Have_a_total_Palette_Multi_of_{x_or_higher_in_Gaming", base: 10, scaling: "exponent", factor: 1.021 },
  { description: "Find_at_least_{_items,_as_shown_by_the_Slab", base: 500, scaling: "linear", factor: 6 },
  { description: "Save_up_{_White_Essence_in_Summoning", base: 1000000000, scaling: "exponent", factor: 1.3 },
  { description: "Reach_a_total_of_{_Total_Career_Wins_in_Summoning", base: 50, scaling: "linear", factor: 2 },
  { description: "Check_a_Crop_Transfer_Ticket_worth_at_least_{_Magic_Beans", base: 10000, scaling: "exponent", factor: 1.06 },
  { description: "Save_up_{_Jade_from_the_Ninja_Castle", base: 1000000, scaling: "exponent", factor: 2.5 },
  { description: "Have_a_total_of_{%_Golden_Food_Bonus,_as_shown_by_The_Beanstalk", base: 500, scaling: "linear", factor: 100 },
  { description: "Find_a_total_of_{_Crops,_as_shown_by_your_Crop_Scientist", base: 70, scaling: "linear", factor: 1 },
  { description: "Have_a_max_damage_range_of_{_crystal_damage,_as_shown_in_Player_Info", base: 100, scaling: "exponent", factor: 1.09 },
  { description: "Have_a_total_Spelunking_POW_of_{_or_more", base: 1000000000, scaling: "exponent", factor: 1.22 },
  { description: "Have_a_Best_Depth_of_at_least_{_in_Chucklemire", base: 40, scaling: "step", factor: 2 },
  { description: "Save_up_{_Coins_in_your_inventory..._like,_money,_those_coins", base: 1000000000, scaling: "exponent", factor: 1.55 },
  { description: "Reach_Showdown_{_or_higher_at_the_Emperor's_Castle_in_World_6", base: 25, scaling: "step", factor: 2 },
  { description: "Save_up_{_Bucks_at_your_Sushi_Station", base: 1000000, scaling: "exponent", factor: 1.34 },
  { description: "Save_up_{_Fish_for_your_pal_Poppy", base: 1000000000, scaling: "exponent", factor: 1.28 },
  { description: "Save_up_{_Meat_Slices_for_best_friend_Bubba", base: 1000000, scaling: "exponent", factor: 1.15 },
];

export const LAB_CHIPS: LabItemInfo[] = [
  { name: "Grounded_Nanochip", rawName: "ConsoleChip0", req: [{"name":"Copper_Ore","rawName":"Copper","amount":20000},{"name":"Turkey_of_Thank","rawName":"CookingM0","amount":100},{"name":"Grasslands","rawName":"CookingSpice0","amount":100}] },
  { name: "Grounded_Motherboard", rawName: "ConsoleChip1", req: [{"name":"Oak_Logs","rawName":"OakTree","amount":30000},{"name":"Egg","rawName":"CookingM1","amount":100},{"name":"Grasslands","rawName":"CookingSpice0","amount":100}] },
  { name: "Grounded_Software", rawName: "ConsoleChip2", req: [{"name":"Goldfish","rawName":"Fish1","amount":20000},{"name":"Pie","rawName":"CookingM3","amount":100},{"name":"Jungle","rawName":"CookingSpice1","amount":100}] },
  { name: "Grounded_Processor", rawName: "ConsoleChip3", req: [{"name":"Pocket_Sand","rawName":"DesertA1","amount":10000},{"name":"Frenk_Fries","rawName":"CookingM4","amount":100},{"name":"Jungle","rawName":"CookingSpice1","amount":100}] },
  { name: "Potato_Chip", rawName: "ConsoleChip4", req: [{"name":"Fly","rawName":"Bug1","amount":20000},{"name":"Corn","rawName":"CookingM6","amount":100},{"name":"Encroaching Forest","rawName":"CookingSpice2","amount":100}] },
  { name: "Conductive_Nanochip", rawName: "ConsoleChip5", req: [{"name":"Veiny_Logs","rawName":"StumpTree","amount":100000},{"name":"Pizza","rawName":"CookingM9","amount":100},{"name":"Tree Interior","rawName":"CookingSpice3","amount":100}] },
  { name: "Conductive_Motherboard", rawName: "ConsoleChip6", req: [{"name":"Gold_Ore","rawName":"Gold","amount":100000},{"name":"Corndog","rawName":"CookingM12","amount":100},{"name":"Stinky Sewers","rawName":"CookingSpice4","amount":100}] },
  { name: "Conductive_Software", rawName: "ConsoleChip7", req: [{"name":"Crabbo","rawName":"Critter2","amount":10000},{"name":"Dango","rawName":"CookingM15","amount":100},{"name":"Stinky Sewers","rawName":"CookingSpice4","amount":100}] },
  { name: "Conductive_Processor", rawName: "ConsoleChip8", req: [{"name":"Mosquisnow","rawName":"Bug5","amount":100000},{"name":"Croissant","rawName":"CookingM18","amount":100},{"name":"Desert Oasis","rawName":"CookingSpice5","amount":100}] },
  { name: "Chocolatey_Chip", rawName: "ConsoleChip9", req: [{"name":"Pinion_Spur","rawName":"CraftMat8","amount":200000},{"name":"Cheese","rawName":"CookingM21","amount":100},{"name":"Beach Docks","rawName":"CookingSpice6","amount":100}] },
  { name: "Galvanic_Nanochip", rawName: "ConsoleChip10", req: [{"name":"Sippy_Straw","rawName":"SnowC1","amount":100000},{"name":"Cheesy_Bread","rawName":"CookingM24","amount":100},{"name":"Coarse Mountains","rawName":"CookingSpice7","amount":100}] },
  { name: "Galvanic_Motherboard", rawName: "ConsoleChip11", req: [{"name":"Skelefish","rawName":"Fish5","amount":250000},{"name":"Riceball","rawName":"CookingM27","amount":100},{"name":"Twilight Desert","rawName":"CookingSpice8","amount":100}] },
  { name: "Galvanic_Software", rawName: "ConsoleChip12", req: [{"name":"Dementia_Ore","rawName":"Dementia","amount":300000},{"name":"Durian_Fruit","rawName":"CookingM29","amount":100},{"name":"The Crypt","rawName":"CookingSpice9","amount":100}] },
  { name: "Galvanic_Processor", rawName: "ConsoleChip13", req: [{"name":"Wurm_Tail","rawName":"GalaxyB2","amount":100000},{"name":"Bunt_Cake","rawName":"CookingM31","amount":100},{"name":"Frosty Peaks","rawName":"CookingSpice10","amount":100}] },
  { name: "Wood_Chip", rawName: "ConsoleChip14", req: [{"name":"Cubed_Logs","rawName":"Tree8","amount":250000},{"name":"Leek","rawName":"CookingM33","amount":100},{"name":"Tundra Outback","rawName":"CookingSpice11","amount":100}] },
  { name: "Silkrode_Nanochip", rawName: "ConsoleChip15", req: [{"name":"Lugi_Bracket","rawName":"CraftMat10","amount":2000000},{"name":"Pretzel","rawName":"CookingM35","amount":100},{"name":"Crystal Caverns","rawName":"CookingSpice12","amount":100}] },
  { name: "Silkrode_Motherboard", rawName: "ConsoleChip16", req: [{"name":"Squishy_Soul","rawName":"Soul5","amount":2000000},{"name":"Mashed_Potato","rawName":"CookingM37","amount":100},{"name":"Pristalle Lake","rawName":"CookingSpice13","amount":100}] },
  { name: "Silkrode_Software", rawName: "ConsoleChip17", req: [{"name":"Fairy","rawName":"Bug8","amount":2000000},{"name":"Wedding_Cake","rawName":"CookingM39","amount":100},{"name":"Pristalle Lake","rawName":"CookingSpice13","amount":100}] },
  { name: "Silkrode_Processor", rawName: "ConsoleChip18", req: [{"name":"Blobfish","rawName":"Critter10","amount":2000000},{"name":"Whipped_Cocoa","rawName":"CookingM41","amount":100},{"name":"Nebulon Mantle","rawName":"CookingSpice14","amount":100}] },
  { name: "Poker_Chip", rawName: "ConsoleChip19", req: [{"name":"PVC_Pipe","rawName":"CraftMat14","amount":2000000},{"name":"Soda","rawName":"CookingM43","amount":100},{"name":"Nebulon Mantle","rawName":"CookingSpice14","amount":100}] },
  { name: "Omega_Nanochip", rawName: "ConsoleChip20", req: [{"name":"Fairy","rawName":"Bug8","amount":10000000},{"name":"Buncha_Banana","rawName":"CookingM45","amount":100},{"name":"Starfield Skies","rawName":"CookingSpice15","amount":100}] },
  { name: "Omega_Motherboard", rawName: "ConsoleChip21", req: [{"name":"Kraken","rawName":"Fish8","amount":10000000},{"name":"Cotton_Candy","rawName":"CookingM47","amount":100},{"name":"Shores of Eternity","rawName":"CookingSpice16","amount":100}] },
];

export const LAB_JEWELS: LabItemInfo[] = [
  { name: "Amethyst_Rhinestone", rawName: "ConsoleJwl0", req: [{"name":"Strung_Jewels","rawName":"Quest66","amount":5},{"name":"Egg","rawName":"CookingM1","amount":2000},{"name":"Grasslands","rawName":"CookingSpice0","amount":200}] },
  { name: "Purple_Navette", rawName: "ConsoleJwl1", req: [{"name":"Googley_Eyes","rawName":"Quest35","amount":5},{"name":"Pie","rawName":"CookingM3","amount":2000},{"name":"Jungle","rawName":"CookingSpice1","amount":200}] },
  { name: "Purple_Rhombol", rawName: "ConsoleJwl2", req: [{"name":"1_HR_Time_Candy","rawName":"Timecandy1","amount":10},{"name":"Spaghetti","rawName":"CookingM5","amount":2000},{"name":"Encroaching Forest","rawName":"CookingSpice2","amount":200}] },
  { name: "Sapphire_Rhinestone", rawName: "ConsoleJwl3", req: [{"name":"Red_Frisbee","rawName":"Quest15","amount":10},{"name":"Garlic_Bread","rawName":"CookingM7","amount":5000},{"name":"Tree Interior","rawName":"CookingSpice3","amount":400}] },
  { name: "Sapphire_Navette", rawName: "ConsoleJwl4", req: [{"name":"Woodular_Circle","rawName":"TreeInterior1b","amount":25},{"name":"Pizza","rawName":"CookingM9","amount":5000},{"name":"Stinky Sewers","rawName":"CookingSpice4","amount":400}] },
  { name: "Sapphire_Rhombol", rawName: "ConsoleJwl5", req: [{"name":"Golden_Plop","rawName":"Sewers1b","amount":30},{"name":"Pancakes","rawName":"CookingM11","amount":5000},{"name":"Desert Oasis","rawName":"CookingSpice5","amount":400}] },
  { name: "Sapphire_Pyramite", rawName: "ConsoleJwl6", req: [{"name":"Guild_Giftbox","rawName":"Quest38","amount":2},{"name":"Cabbage","rawName":"CookingM13","amount":5000},{"name":"Beach Docks","rawName":"CookingSpice6","amount":400}] },
  { name: "Pyrite_Rhinestone", rawName: "ConsoleJwl7", req: [{"name":"Glass_Shard","rawName":"DesertA1b","amount":50},{"name":"Dango","rawName":"CookingM15","amount":10000},{"name":"Coarse Mountains","rawName":"CookingSpice7","amount":1500}] },
  { name: "Pyrite_Navette", rawName: "ConsoleJwl8", req: [{"name":"Trimmed_Rune_Platelegs","rawName":"EquipmentPants19","amount":2},{"name":"Octoplop","rawName":"CookingM17","amount":10000},{"name":"Twilight Desert","rawName":"CookingSpice8","amount":1500}] },
  { name: "Pyrite_Rhombol", rawName: "ConsoleJwl9", req: [{"name":"Nuget_Cake","rawName":"DesertA3b","amount":50},{"name":"Canopy","rawName":"CookingM19","amount":10000},{"name":"The Crypt","rawName":"CookingSpice9","amount":1500}] },
  { name: "Pyrite_Pyramite", rawName: "ConsoleJwl10", req: [{"name":"Ghost","rawName":"DesertC2b","amount":50},{"name":"Cheese","rawName":"CookingM21","amount":10000},{"name":"Frosty Peaks","rawName":"CookingSpice10","amount":1500}] },
  { name: "Emerald_Rhinestone", rawName: "ConsoleJwl11", req: [{"name":"Baba_Yaga_Baby_Eggs","rawName":"BabaYagaETC","amount":1},{"name":"Eggplant","rawName":"CookingM23","amount":25000},{"name":"Tundra Outback","rawName":"CookingSpice11","amount":5000}] },
  { name: "Emerald_Navette", rawName: "ConsoleJwl12", req: [{"name":"Yellow_Snowflake","rawName":"SnowA2a","amount":80},{"name":"Wild_Boar","rawName":"CookingM25","amount":25000},{"name":"Crystal Caverns","rawName":"CookingSpice12","amount":5000}] },
  { name: "Emerald_Rhombol", rawName: "ConsoleJwl13", req: [{"name":"Ice_Age_3","rawName":"SnowB2a","amount":120},{"name":"Riceball","rawName":"CookingM27","amount":25000},{"name":"Pristalle Lake","rawName":"CookingSpice13","amount":5000}] },
  { name: "Emerald_Pyramite", rawName: "ConsoleJwl14", req: [{"name":"Black_Lense","rawName":"SnowC4a","amount":150},{"name":"Durian_Fruit","rawName":"CookingM29","amount":25000},{"name":"Nebulon Mantle","rawName":"CookingSpice14","amount":5000}] },
  { name: "Emerald_Ulthurite", rawName: "ConsoleJwl15", req: [{"name":"Lost_Batteries","rawName":"GalaxyA2b","amount":200},{"name":"Bunt_Cake","rawName":"CookingM31","amount":25000},{"name":"Starfield Skies","rawName":"CookingSpice15","amount":5000}] },
  { name: "Black_Diamond_Rhinestone", rawName: "ConsoleJwl16", req: [{"name":"Pearler_Shell","rawName":"GalaxyC1b","amount":300},{"name":"Leek","rawName":"CookingM33","amount":100000},{"name":"Starfield Skies","rawName":"CookingSpice15","amount":10000}] },
  { name: "Black_Diamond_Ulthurite", rawName: "ConsoleJwl17", req: [{"name":"Voodofish","rawName":"Critter10A","amount":10000},{"name":"Pretzel","rawName":"CookingM35","amount":100000},{"name":"Shores of Eternity","rawName":"CookingSpice16","amount":10000}] },
  { name: "Pure_Opal_Rhinestone", rawName: "ConsoleJwl18", req: [{"name":"Leafy_Droplet","rawName":"SpiA1","amount":3000000},{"name":"Ratatouey","rawName":"CookingM53","amount":1000000},{"rawName":"CookingSpice20","amount":10000}] },
  { name: "Pure_Opal_Navette", rawName: "ConsoleJwl19", req: [{"name":"Dark_Lantern","rawName":"SpiB2b","amount":1000},{"name":"Sticky_Bun","rawName":"CookingM58","amount":10000000},{"rawName":"CookingSpice21","amount":10000}] },
  { name: "Pure_Opal_Rhombol", rawName: "ConsoleJwl20", req: [{"name":"Tottoise","rawName":"Critter11A","amount":5000},{"name":"Bill_Jack_Pep","rawName":"CookingM62","amount":100000000},{"rawName":"CookingSpice22","amount":10000}] },
  { name: "Deadly_Wrath_Jewel", rawName: "ConsoleJwl21", req: [{"name":"Dark_Lantern","rawName":"SpiB2b","amount":1000},{"name":"Sticky_Bun","rawName":"CookingM58","amount":10000000},{"rawName":"CookingSpice21","amount":10000}] },
  { name: "North_Winds_Jewel", rawName: "ConsoleJwl22", req: [{"name":"Dark_Lantern","rawName":"SpiB2b","amount":1000},{"name":"Sticky_Bun","rawName":"CookingM58","amount":10000000},{"rawName":"CookingSpice21","amount":10000}] },
  { name: "Eternal_Energy_Jewel", rawName: "ConsoleJwl23", req: [{"name":"Dark_Lantern","rawName":"SpiB2b","amount":1000},{"name":"Sticky_Bun","rawName":"CookingM58","amount":10000000},{"rawName":"CookingSpice21","amount":10000}] },
];

/** Killroy randomList 68, 69, 70, 71, 72 (lava), 99 (spirit) resolved to enemy rawNames. */
export const KILLROY_ENEMY_LISTS: string[][] = [
  [
    "mushG",
    "frogG",
    "poopSmall",
    "branch",
    "beanG",
    "ratB",
    "slimeG",
    "mushR",
    "acorn",
    "snakeG",
    "carrotO",
    "goblinG",
    "plank",
    "frogBIG",
    "mushW"
  ],
  [
    "jarSand",
    "mimicA",
    "crabcake",
    "coconut",
    "sandcastle",
    "pincermin",
    "potato",
    "steak",
    "moonman",
    "sandgiant",
    "snailZ"
  ],
  [
    "sheep",
    "flake",
    "stache",
    "bloque",
    "mamoth",
    "snowball",
    "penguin",
    "thermostat",
    "glass",
    "snakeB",
    "speaker",
    "eye",
    "ram"
  ],
  [
    "mushP",
    "w4a2",
    "w4a3",
    "demonP",
    "w4b2",
    "w4b1",
    "w4b3",
    "w4b4",
    "w4b5",
    "w4c1",
    "w4c2",
    "w4c3",
    "w4c4"
  ],
  [
    "w5a1",
    "w5a2",
    "w5a3",
    "w5a4",
    "w5a5",
    "w5b1",
    "w5b2",
    "w5b3",
    "w5b4",
    "w5b5",
    "w5b6",
    "w5c1",
    "w5c2"
  ],
  [
    "w6a1",
    "w6a2",
    "w6a3",
    "w6a4",
    "w6a5",
    "w6b1",
    "w6b2",
    "w6b3",
    "w6b4",
    "w6c1",
    "w6c2",
    "w6d1",
    "w6d2",
    "w6d3"
  ]
];

export const KILLROY_ENEMY_NAMES: Record<string, string> = {
  acorn: "Nutto",
  beanG: "Bored_Bean",
  bloque: "Bloque",
  branch: "Walking_Stick",
  carrotO: "Carrotman",
  coconut: "Mafioso",
  crabcake: "Crabcake",
  demonP: "Demon_Genie",
  eye: "Neyeptune",
  flake: "Frost_Flake",
  frogBIG: "Gigafrog",
  frogG: "Frog",
  glass: "Quenchie",
  goblinG: "Glublin",
  jarSand: "Sandy_Pot",
  mamoth: "Mamooth",
  mimicA: "Mimic",
  moonman: "Moonmoon",
  mushG: "Green_Mushroom",
  mushP: "Purp_Mushroom",
  mushR: "Red_Mushroom",
  mushW: "Wood_Mushroom",
  penguin: "Penguin",
  pincermin: "Pincermin",
  plank: "Wode_Board",
  poopSmall: "Poop",
  potato: "Mashed_Potato",
  ram: "Dedotated_Ram",
  ratB: "Rat",
  sandcastle: "Sand_Castle",
  sandgiant: "Sand_Giant",
  sheep: "Sheepie",
  slimeG: "Slime",
  snailZ: "Snelbie",
  snakeB: "Cryosnake",
  snakeG: "Baby_Boa",
  snowball: "Snowman",
  speaker: "Bop_Box",
  stache: "Sir_Stache",
  steak: "Tyson",
  thermostat: "Thermister",
  w4a2: "TV",
  w4a3: "Donut",
  w4b1: "Flying_Worm",
  w4b2: "Soda_Can",
  w4b3: "Gelatinous_Cuboid",
  w4b4: "Choccie",
  w4b5: "Biggole_Wurm",
  w4c1: "Clammie",
  w4c2: "Octodar",
  w4c3: "Flombeige",
  w4c4: "Stilted_Seeker",
  w5a1: "Suggma",
  w5a2: "Maccie",
  w5a3: "Mister_Brightside",
  w5a4: "Cheese_Nub",
  w5a5: "Stiltmole",
  w5b1: "Molti",
  w5b2: "Purgatory_Stalker",
  w5b3: "Citringe",
  w5b4: "Lampar",
  w5b5: "Fire_Spirit",
  w5b6: "Biggole_Mole",
  w5c1: "Crawler",
  w5c2: "Tremor_Wurm",
  w6a1: "Sprout_Spirit",
  w6a2: "Ricecake",
  w6a3: "River_Spirit",
  w6a4: "Baby_Troll",
  w6a5: "Woodlin_Spirit",
  w6b1: "Bamboo_Spirit",
  w6b2: "Lantern_Spirit",
  w6b3: "Mama_Troll",
  w6b4: "Leek_Spirit",
  w6c1: "Ceramic_Spirit",
  w6c2: "Skydoggie_Spirit",
  w6d1: "Royal_Egg",
  w6d2: "Minichief_Spirit",
  w6d3: "Samurai_Guardian"
};

export const DUNGEON_TRAITS: { section: string; levelReq: number; bonusCount: number }[] = [
  { section: "Beginner Traits", levelReq: 5, bonusCount: 3 },
  { section: "Kinda Cool Traits", levelReq: 10, bonusCount: 3 },
  { section: "Strategery Traits", levelReq: 15, bonusCount: 4 },
  { section: "Da Cred Traits", levelReq: 20, bonusCount: 2 },
  { section: "Drop Drip Traits", levelReq: 25, bonusCount: 4 },
  { section: "Cash Money Traits", levelReq: 30, bonusCount: 3 },
  { section: "ChOiIiCe Traits", levelReq: 35, bonusCount: 3 },
  { section: "Royale Traits", levelReq: 40, bonusCount: 2 },
  { section: "Endothelium Traits", levelReq: 50, bonusCount: 4 }
];

/** randomList[29] dungeon rank XP thresholds. Rank is 1 + last index where progress > req. */
export const DUNGEON_RANK_REQS: number[] = [
  0, 4, 10, 18, 28, 40, 70, 110, 160, 230, 320, 470, 670, 940, 1310, 1760, 2400, 3250, 4000, 5000, 6160, 8000, 10000,
  12500, 15000, 18400, 21000, 25500, 30500, 36500, 45400, 52000, 61000, 72500, 85000, 110000, 125000, 145000, 170000,
  200000, 250000, 275000, 325000, 400000, 490000, 600000, 725000, 875000, 1000000, 1200000, 1500000, 3000000, 5000000,
  10000000, 20000000, 30000000, 40000000, 50000000, 60000000, 80000000, 100000000, 120000000, 150000000, 200000000,
  250000000, 300000000, 400000000, 500000000, 600000000, 800000000, 1000000000, 1200000000, 1400000000, 1600000000,
  1800000000, 2000000000
];

