/** Compact Idleon Toolbox catalogs used by Dashboard account alerts. Generated from IT website-data. */
export type StampGoldInfo = { rawName: string; base: number; pow: number; req: number };
export type NamedRaw = { rawName: string; name: string };
export type VialInfo = { name: string; mainItem: string; liquid: string };
export type RefineryCost = { rawName: string; quantity: number };
export type RefinerySaltInfo = { rawName: string; saltName: string; cost: RefineryCost[] };
export type SigilInfo = { name: string; boostCost: number; jadeCost: number; etherealCost: number; eclecticCost: number };
export type PoppyUpgrade = { name: string; x1: number; x2: number; x3: number };

export const STAMP_GOLD: (StampGoldInfo | null)[][] = [
  [
    { rawName: "StampA1", base: 10, pow: 1.2, req: 5 },
    { rawName: "StampA2", base: 15, pow: 1.2, req: 5 },
    { rawName: "StampA3", base: 30, pow: 1.2, req: 5 },
    { rawName: "StampA4", base: 50, pow: 1.3, req: 4 },
    { rawName: "StampA5", base: 50, pow: 1.3, req: 5 },
    { rawName: "StampA6", base: 50, pow: 1.3, req: 5 },
    { rawName: "StampA7", base: 50, pow: 1.3, req: 4 },
    { rawName: "StampA8", base: 50, pow: 1.3, req: 3 },
    { rawName: "StampA9", base: 50, pow: 1.3, req: 2 },
    { rawName: "StampA10", base: 50, pow: 1.3, req: 4 },
    { rawName: "StampA11", base: 50, pow: 1.3, req: 2 },
    { rawName: "StampA12", base: 50, pow: 1.3, req: 4 },
    { rawName: "StampA13", base: 50, pow: 1.35, req: 2 },
    { rawName: "StampA14", base: 75, pow: 1.32, req: 3 },
    { rawName: "StampA15", base: 300, pow: 1.38, req: 2 },
    { rawName: "StampA16", base: 2000, pow: 1.33, req: 4 },
    { rawName: "StampA17", base: 5000, pow: 1.36, req: 5 },
    { rawName: "StampA18", base: 2500, pow: 1.3, req: 5 },
    { rawName: "StampA19", base: 3000, pow: 1.3, req: 6 },
    { rawName: "StampA20", base: 10000, pow: 1.3, req: 3 },
    { rawName: "StampA21", base: 2200, pow: 1.305, req: 7 },
    { rawName: "StampA22", base: 10000, pow: 1.3, req: 3 },
    { rawName: "StampA23", base: 10000, pow: 1.34, req: 10 },
    { rawName: "StampA24", base: 1550, pow: 1.36, req: 3 },
    { rawName: "StampA25", base: 15000, pow: 1.33, req: 5 },
    { rawName: "StampA26", base: 10000, pow: 1.32, req: 10 },
    { rawName: "StampA27", base: 25000, pow: 1.39, req: 4 },
    { rawName: "StampA28", base: 2000, pow: 1.36, req: 2 },
    { rawName: "StampA29", base: 2000000, pow: 1.43, req: 6 },
    { rawName: "StampA30", base: 3000000, pow: 1.47, req: 10 },
    { rawName: "StampA31", base: 1500000, pow: 1.4, req: 10 },
    { rawName: "StampA32", base: 1000000, pow: 1.4, req: 15 },
    { rawName: "StampA33", base: 100000000, pow: 1.4, req: 7 },
    { rawName: "StampA34", base: 100000000, pow: 1.4, req: 7 },
    { rawName: "StampA35", base: 100000000, pow: 1.4, req: 7 },
    { rawName: "StampA36", base: 100000000, pow: 1.4, req: 10 },
    { rawName: "StampA37", base: 200000000, pow: 1.43, req: 10 },
    { rawName: "StampA38", base: 10000000, pow: 1.43, req: 10 },
    { rawName: "StampA39", base: 25000000, pow: 1.36, req: 2 },
    { rawName: "StampA40", base: 2500000000, pow: 1.36, req: 10 },
    { rawName: "StampA41", base: 66000000000, pow: 1.36, req: 15 },
    { rawName: "StampA42", base: 2200000000000, pow: 1.36, req: 10 },
    { rawName: "StampA43", base: 660000000000000, pow: 1.36, req: 15 },
    { rawName: "StampA44", base: 6.6e+16, pow: 1.45, req: 15 }
  ],
  [
    { rawName: "StampB1", base: 10, pow: 1.2, req: 10 },
    { rawName: "StampB2", base: 10, pow: 1.2, req: 10 },
    { rawName: "StampB3", base: 50, pow: 1.3, req: 5 },
    { rawName: "StampB4", base: 50, pow: 1.3, req: 10 },
    { rawName: "StampB5", base: 10000, pow: 1.3, req: 5 },
    { rawName: "StampB6", base: 50, pow: 1.3, req: 10 },
    { rawName: "StampB7", base: 20000, pow: 1.3, req: 5 },
    { rawName: "StampB8", base: 50, pow: 1.3, req: 10 },
    { rawName: "StampB9", base: 80, pow: 1.35, req: 5 },
    { rawName: "StampB10", base: 35000, pow: 1.4, req: 10 },
    { rawName: "StampB11", base: 80, pow: 1.35, req: 5 },
    { rawName: "StampB12", base: 50000, pow: 1.36, req: 10 },
    { rawName: "StampB13", base: 800, pow: 1.29, req: 4 },
    { rawName: "StampB14", base: 1250, pow: 1.28, req: 5 },
    { rawName: "StampB15", base: 1000, pow: 1.3, req: 5 },
    { rawName: "StampB16", base: 2500, pow: 1.3, req: 2 },
    { rawName: "StampB17", base: 1000, pow: 1.32, req: 5 },
    { rawName: "StampB18", base: 1500, pow: 1.33, req: 5 },
    { rawName: "StampB19", base: 1000, pow: 1.3, req: 5 },
    { rawName: "StampB20", base: 1500, pow: 1.33, req: 5 },
    { rawName: "StampB21", base: 1000, pow: 1.3, req: 8 },
    { rawName: "StampB22", base: 1500, pow: 1.3, req: 5 },
    { rawName: "StampB23", base: 1000, pow: 1.3, req: 8 },
    { rawName: "StampB24", base: 1500, pow: 1.3, req: 5 },
    { rawName: "StampB25", base: 7500, pow: 1.3, req: 10 },
    { rawName: "StampB26", base: 10000, pow: 1.3, req: 5 },
    { rawName: "StampB27", base: 12500, pow: 1.3, req: 3 },
    { rawName: "StampB28", base: 15000, pow: 1.3, req: 3 },
    { rawName: "StampB29", base: 10000, pow: 1.3, req: 3 },
    { rawName: "StampB30", base: 10000, pow: 1.3, req: 4 },
    { rawName: "StampB31", base: 15000, pow: 1.3, req: 3 },
    { rawName: "StampB32", base: 50000, pow: 1.5, req: 4 },
    { rawName: "StampB33", base: 7500, pow: 1.3, req: 10 },
    { rawName: "StampB34", base: 15000, pow: 1.3, req: 2 },
    { rawName: "StampB35", base: 10000, pow: 1.3, req: 2 },
    { rawName: "StampB36", base: 6000, pow: 1.3, req: 6 },
    { rawName: "StampB37", base: 1000000, pow: 1.35, req: 15 },
    { rawName: "StampB38", base: 1000000, pow: 1.35, req: 15 },
    { rawName: "StampB39", base: 1000000, pow: 1.35, req: 10 },
    { rawName: "StampB40", base: 1000000, pow: 1.4, req: 10 },
    { rawName: "StampB41", base: 1000000, pow: 1.4, req: 15 },
    { rawName: "StampB42", base: 1000000, pow: 1.35, req: 10 },
    { rawName: "StampB43", base: 500000000, pow: 1.35, req: 5 },
    { rawName: "StampB44", base: 500000000, pow: 1.35, req: 5 },
    { rawName: "StampB45", base: 500000000, pow: 1.35, req: 8 },
    { rawName: "StampB46", base: 800000000, pow: 1.35, req: 10 },
    { rawName: "StampB47", base: 800000000, pow: 1.35, req: 2 },
    { rawName: "StampB48", base: 100000000000, pow: 1.37, req: 5 },
    { rawName: "StampB49", base: 50000000000, pow: 1.37, req: 8 },
    { rawName: "StampB50", base: 20000000000, pow: 1.37, req: 10 },
    { rawName: "StampB51", base: 50000000000, pow: 1.37, req: 8 },
    { rawName: "StampB52", base: 60000000000, pow: 1.37, req: 8 },
    { rawName: "StampB53", base: 800000000000, pow: 1.37, req: 8 },
    { rawName: "StampB54", base: 12000000000000, pow: 1.37, req: 8 },
    { rawName: "StampB55", base: 1200000000000000.0, pow: 1.37, req: 8 },
    { rawName: "StampB56", base: 1200000000000000.0, pow: 1.37, req: 8 },
    { rawName: "StampB57", base: 1200000000000000.0, pow: 1.37, req: 8 }
  ],
  [
    { rawName: "StampC1", base: 500, pow: 1.32, req: 10 },
    { rawName: "StampC2", base: 4000, pow: 1.28, req: 4 },
    { rawName: "StampC3", base: 800, pow: 1.31, req: 10 },
    { rawName: "StampC4", base: 1500, pow: 1.33, req: 10 },
    { rawName: "StampC5", base: 1000, pow: 1.33, req: 10 },
    { rawName: "StampC6", base: 1500, pow: 1.305, req: 5 },
    { rawName: "StampC7", base: 3000, pow: 1.3, req: 4 },
    { rawName: "StampC8", base: 1000, pow: 1.32, req: 5 },
    { rawName: "StampC9", base: 1200, pow: 1.31, req: 10 },
    { rawName: "StampC10", base: 5000000000000, pow: 1.3, req: 10 },
    { rawName: "StampC11", base: 30000, pow: 1.5, req: 10 },
    { rawName: "StampC12", base: 1000000, pow: 1.32, req: 12 },
    { rawName: "StampC13", base: 2000, pow: 1.4, req: 2 },
    { rawName: "StampC14", base: 4000, pow: 1.35, req: 2 },
    { rawName: "StampC15", base: 40000, pow: 1.35, req: 2 },
    { rawName: "StampC16", base: 300000000, pow: 1.4, req: 2 },
    { rawName: "StampC17", base: 50, pow: 1.3, req: 2 },
    { rawName: "StampC18", base: 50, pow: 1.3, req: 2 },
    { rawName: "StampC19", base: 10000, pow: 1.3, req: 2 },
    { rawName: "StampC20", base: 12500, pow: 1.3, req: 2 },
    { rawName: "StampC21", base: 1000000, pow: 1.6, req: 3 },
    { rawName: "StampC22", base: 25000000, pow: 1.52, req: 5 },
    { rawName: "StampC23", base: 25000000, pow: 1.52, req: 8 },
    { rawName: "StampC24", base: 2000000000, pow: 1.72, req: 20 },
    { rawName: "StampC25", base: 2000000000, pow: 1.72, req: 15 },
    { rawName: "StampC26", base: 2e+18, pow: 4.5, req: 1 },
    { rawName: "StampC27", base: 20000000000000, pow: 1.72, req: 15 }
  ]
];

export const VIAL_INFO: (VialInfo | null)[] = [
  { name: "COPPER_CORONA", mainItem: "Copper", liquid: "Liquid1" },
  { name: "SIPPY_SPLINTERS", mainItem: "OakTree", liquid: "Liquid1" },
  { name: "MUSHROOM_SOUP", mainItem: "Grasslands1", liquid: "Liquid1" },
  { name: "SPOOL_SPRITE", mainItem: "CraftMat1", liquid: "Liquid1" },
  { name: "BARIUM_MIXTURE", mainItem: "CopperBar", liquid: "Liquid1" },
  { name: "DIETER_DRINK", mainItem: "Grasslands3", liquid: "Liquid1" },
  { name: "SKINNY_0_CAL", mainItem: "Jungle2", liquid: "Liquid1" },
  { name: "THUMB_POW", mainItem: "CraftMat5", liquid: "Liquid1" },
  { name: "JUNGLE_JUICE", mainItem: "JungleTree", liquid: "Liquid1" },
  { name: "BARLEY_BREW", mainItem: "IronBar", liquid: "Liquid1" },
  { name: "ANEARFUL", mainItem: "Forest1", liquid: "Liquid1" },
  { name: "TEA_WITH_PEA", mainItem: "ToiletTree", liquid: "Liquid1" },
  { name: "GOLD_GUZZLE", mainItem: "Gold", liquid: "Liquid1" },
  { name: "RAMIFICOCTION", mainItem: "Forest3", liquid: "Liquid1" },
  { name: "SEAWATER", mainItem: "Fish1", liquid: "Liquid1" },
  { name: "TAIL_TIME", mainItem: "Sewers2", liquid: "Liquid1" },
  { name: "FLY_IN_MY_DRINK", mainItem: "Bug1", liquid: "Liquid1" },
  { name: "MIMICRAUGHT", mainItem: "DesertA2", liquid: "Liquid1" },
  { name: "BLUE_FLAV", mainItem: "Plat", liquid: "Liquid1" },
  { name: "SLUG_SLURP", mainItem: "Fish2", liquid: "Liquid1" },
  { name: "PICKLE_JAR", mainItem: "BobJoePickle", liquid: "Liquid2" },
  { name: "FUR_REFRESHER", mainItem: "SnowA1", liquid: "Liquid2" },
  { name: "SIPPY_SOUL", mainItem: "Soul1", liquid: "Liquid2" },
  { name: "CRAB_JUICE", mainItem: "Critter2", liquid: "Liquid2" },
  { name: "VOID_VIAL", mainItem: "Void", liquid: "Liquid2" },
  { name: "RED_MALT", mainItem: "Refinery1", liquid: "Liquid2" },
  { name: "EW_GROSS_GROSS", mainItem: "Bug5", liquid: "Liquid2" },
  { name: "THE_SPANISH_SAHARA", mainItem: "SaharanFoal", liquid: "Liquid2" },
  { name: "POISON_TINCTURE", mainItem: "Critter1A", liquid: "Liquid2" },
  { name: "ETRUSCAN_LAGER", mainItem: "SnowB2", liquid: "Liquid2" },
  { name: "CHONKER_CHUG", mainItem: "Soul2", liquid: "Liquid2" },
  { name: "BUBONIC_BURP", mainItem: "Critter4", liquid: "Liquid3" },
  { name: "VISIBLE_INK", mainItem: "SnowB3", liquid: "Liquid3" },
  { name: "ORANGE_MALT", mainItem: "Refinery2", liquid: "Liquid3" },
  { name: "SNOW_SLURRY", mainItem: "SnowB5", liquid: "Liquid3" },
  { name: "SLOWERGY_DRINK", mainItem: "Soul4", liquid: "Liquid3" },
  { name: "SIPPY_CUP", mainItem: "SnowC1", liquid: "Liquid3" },
  { name: "BUNNY_BREW", mainItem: "Critter7", liquid: "Liquid3" },
  { name: "40-40_PURITY", mainItem: "SnowC4", liquid: "Liquid3" },
  { name: "SHAVED_ICE", mainItem: "Refinery5", liquid: "Liquid3" },
  { name: "GOOSEY_GLUG", mainItem: "Critter9", liquid: "Liquid3" },
  { name: "BALL_PICKLE_JAR", mainItem: "BallJoePickle", liquid: "Liquid1" },
  { name: "CAPACHINO", mainItem: "GalaxyA1", liquid: "Liquid3" },
  { name: "DONUT_DRINK", mainItem: "GalaxyA3", liquid: "Liquid3" },
  { name: "LONG_ISLAND_TEA", mainItem: "Fish6", liquid: "Liquid3" },
  { name: "SPOOK_PINT", mainItem: "Soul5", liquid: "Liquid3" },
  { name: "CALCIUM_CARBONATE", mainItem: "GalaxyB3", liquid: "Liquid3" },
  { name: "BLOAT_DRAFT", mainItem: "Critter10", liquid: "Liquid3" },
  { name: "CHOCO_MILKSHAKE", mainItem: "GalaxyB4", liquid: "Liquid3" },
  { name: "PEARL_SELTZER", mainItem: "GalaxyC1b", liquid: "Liquid3" },
  { name: "KRAKENADE", mainItem: "Fish8", liquid: "Liquid3" },
  { name: "ELECTROLYTE", mainItem: "GalaxyC4", liquid: "Liquid3" },
  { name: "ASH_AGUA", mainItem: "LavaA1", liquid: "Liquid3" },
  { name: "MAPLE_SYRUP", mainItem: "Tree9", liquid: "Liquid3" },
  { name: "HAMPTER_DRIPPY", mainItem: "LavaA5b", liquid: "Liquid3" },
  { name: "DREADNOG", mainItem: "DreadloBar", liquid: "Liquid3" },
  { name: "DUSTED_DRINK", mainItem: "Bug10", liquid: "Liquid3" },
  { name: "OJ_JOOCE", mainItem: "LavaB3", liquid: "Liquid3" },
  { name: "OOZIE_OOBLEK", mainItem: "Soul6", liquid: "Liquid3" },
  { name: "VENISON_MALT", mainItem: "LavaC2", liquid: "Liquid3" },
  { name: "MARBLE_MOCHA", mainItem: "Marble", liquid: "Liquid3" },
  { name: "WILLOW_SIPPY", mainItem: "Tree11", liquid: "Liquid3" },
  { name: "SHINYFIN_STEW", mainItem: "Fish13", liquid: "Liquid3" },
  { name: "DREAMY_DRINK", mainItem: "Bug11", liquid: "Liquid3" },
  { name: "RICECAKORADE", mainItem: "SpiA2", liquid: "Liquid4" },
  { name: "LADYBUG_SERUM", mainItem: "Bug12", liquid: "Liquid4" },
  { name: "FLAVORGIL", mainItem: "Fish12", liquid: "Liquid4" },
  { name: "GREENLEAF_TEA", mainItem: "SpiB1", liquid: "Liquid4" },
  { name: "FIREFLY_GROG", mainItem: "Bug13", liquid: "Liquid4" },
  { name: "DABAR_SPECIAL", mainItem: "GodshardBar", liquid: "Liquid4" },
  { name: "REFRESHMENT", mainItem: "Soul7", liquid: "Liquid4" },
  { name: "GIBBED_DRINK", mainItem: "SpiC2", liquid: "Liquid4" },
  { name: "DED_SAP", mainItem: "Tree13", liquid: "Liquid4" },
  { name: "ROYALE_COLA", mainItem: "SpiD3", liquid: "Liquid4" },
  { name: "TURTLE_TISANE", mainItem: "Critter11", liquid: "Liquid4" },
  { name: "CHAPTER_CHUG", mainItem: "Spelunking0", liquid: "Liquid4" },
  { name: "SIPPY_SEAWEED", mainItem: "Tree14", liquid: "Liquid4" },
  { name: "WRIGGLE_WATER", mainItem: "w7A3", liquid: "Liquid4" },
  { name: "ROCKY_BOBA", mainItem: "Prehistrium", liquid: "Liquid4" },
  { name: "OCTOSODA", mainItem: "Soul8", liquid: "Liquid4" },
  { name: "PAPER_PINT", mainItem: "Spelunking2", liquid: "Liquid4" },
  { name: "SCALE_ON_ICE", mainItem: "w7A5", liquid: "Liquid4" },
  { name: "TRASH_DRANK", mainItem: "Bug15", liquid: "Liquid4" },
  { name: "CRABOMAYSE", mainItem: "w7A12", liquid: "Liquid4" },
  { name: "SHIPINABOTTLE", mainItem: "w7B12b", liquid: "Liquid4" },
  { name: "CANTEEN_READ", mainItem: "Spelunking5", liquid: "Liquid4" }
];

export const VIAL_COSTS = [0, 100, 1e3, 2500, 1e4, 5e4, 1e5, 5e5, 1000001, 5e6, 25e6, 1e8, 1e9, 5e10];
export const MAX_VIAL_LEVEL = 13;

export const MEAL_INFO: NamedRaw[] = [
  { name: "Turkey_of_Thank", rawName: "CookingMB0" },
  { name: "Egg", rawName: "CookingMB1" },
  { name: "Salad", rawName: "CookingMB2" },
  { name: "Pie", rawName: "CookingMB3" },
  { name: "Frenk_Fries", rawName: "CookingMB4" },
  { name: "Spaghetti", rawName: "CookingMB5" },
  { name: "Corn", rawName: "CookingMB6" },
  { name: "Garlic_Bread", rawName: "CookingMB7" },
  { name: "Garlicles_Bread", rawName: "CookingMB8" },
  { name: "Pizza", rawName: "CookingMB9" },
  { name: "Apple", rawName: "CookingMB10" },
  { name: "Pancakes", rawName: "CookingMB11" },
  { name: "Corndog", rawName: "CookingMB12" },
  { name: "Cabbage", rawName: "CookingMB13" },
  { name: "Potato_P_Pastry", rawName: "CookingMB14" },
  { name: "Dango", rawName: "CookingMB15" },
  { name: "Sourish_Fish", rawName: "CookingMB16" },
  { name: "Octoplop", rawName: "CookingMB17" },
  { name: "Croissant", rawName: "CookingMB18" },
  { name: "Canopy", rawName: "CookingMB19" },
  { name: "Cannoli", rawName: "CookingMB20" },
  { name: "Cheese", rawName: "CookingMB21" },
  { name: "Sawdust", rawName: "CookingMB22" },
  { name: "Eggplant", rawName: "CookingMB23" },
  { name: "Cheesy_Bread", rawName: "CookingMB24" },
  { name: "Wild_Boar", rawName: "CookingMB25" },
  { name: "Donut", rawName: "CookingMB26" },
  { name: "Riceball", rawName: "CookingMB27" },
  { name: "Cauliflower", rawName: "CookingMB28" },
  { name: "Durian_Fruit", rawName: "CookingMB29" },
  { name: "Orange", rawName: "CookingMB30" },
  { name: "Bunt_Cake", rawName: "CookingMB31" },
  { name: "Chocala_Truffle", rawName: "CookingMB32" },
  { name: "Leek", rawName: "CookingMB33" },
  { name: "Fortune_Cookie", rawName: "CookingMB34" },
  { name: "Pretzel", rawName: "CookingMB35" },
  { name: "Sea_Urchin", rawName: "CookingMB36" },
  { name: "Mashed_Potato", rawName: "CookingMB37" },
  { name: "Mutton", rawName: "CookingMB38" },
  { name: "Wedding_Cake", rawName: "CookingMB39" },
  { name: "Eel", rawName: "CookingMB40" },
  { name: "Whipped_Cocoa", rawName: "CookingMB41" },
  { name: "Onion", rawName: "CookingMB42" },
  { name: "Soda", rawName: "CookingMB43" },
  { name: "Sushi_Roll", rawName: "CookingMB44" },
  { name: "Buncha_Banana", rawName: "CookingMB45" },
  { name: "Pumpkin", rawName: "CookingMB46" },
  { name: "Cotton_Candy", rawName: "CookingMB47" },
  { name: "Massive_Fig", rawName: "CookingMB48" },
  { name: "Chef_Geustloaf", rawName: "CookingMB49" },
  { name: "Kiwi_Fruit", rawName: "CookingMB50" },
  { name: "Popped_Corn", rawName: "CookingMB51" },
  { name: "Double_Cherry", rawName: "CookingMB52" },
  { name: "Ratatouey", rawName: "CookingMB53" },
  { name: "Giant_Tomato", rawName: "CookingMB54" },
  { name: "Wrath_Grapes", rawName: "CookingMB55" },
  { name: "Sausy_Sausage", rawName: "CookingMB56" },
  { name: "Seasoned_Marrow", rawName: "CookingMB57" },
  { name: "Sticky_Bun", rawName: "CookingMB58" },
  { name: "Frazzleberry", rawName: "CookingMB59" },
  { name: "MrLoin_Steak", rawName: "CookingMB60" },
  { name: "Large_Pohayoh", rawName: "CookingMB61" },
  { name: "Bill_Jack_Pep", rawName: "CookingMB62" },
  { name: "Burned_Mello", rawName: "CookingMB63" },
  { name: "Yumi_Peachring", rawName: "CookingMB64" },
  { name: "Plumpcakes", rawName: "CookingMB65" },
  { name: "Nyanborgir", rawName: "CookingMB66" },
  { name: "Tempura_Shrimp", rawName: "CookingMB67" },
  { name: "Woahtermelon", rawName: "CookingMB68" },
  { name: "Cookies", rawName: "CookingMB69" },
  { name: "Singing_Seed", rawName: "CookingMB70" },
  { name: "Tasty_Treat", rawName: "CookingMB71" },
  { name: "Giga_Chip", rawName: "CookingMB72" },
  { name: "Divorce_Cake", rawName: "CookingMB73" }
];

export const PREMIUM_HATS: NamedRaw[] = [
  { rawName: "EquipmentHatsBeg1", name: "Ice_Cream_Sundae" },
  { rawName: "EquipmentHats10", name: "Pink_Headband" },
  { rawName: "EquipmentHats84", name: "The_Crow_Perch" },
  { rawName: "EquipmentHats21", name: "Birthday_Hat" },
  { rawName: "EquipmentHats24", name: "Farmer_Brimest" },
  { rawName: "EquipmentHats107", name: "Shiny_Bored_Beanie" },
  { rawName: "EquipmentHats42", name: "Santa_Hat" },
  { rawName: "EquipmentHats111", name: "Epic_Santa_Hat" },
  { rawName: "EquipmentHats51", name: "Big_Pretty_Bow" },
  { rawName: "EquipmentHats55", name: "Steam_Cap" },
  { rawName: "EquipmentHats108", name: "3rd_Anniversary_Ice_Cream_Topper" },
  { rawName: "EquipmentHats56", name: "Bunny_Ears" },
  { rawName: "EquipmentHats63", name: "Summer_Shell" },
  { rawName: "EquipmentHats64", name: "Nuget_Cake_Fedora" },
  { rawName: "EquipmentHats66", name: "Honker_Hat" },
  { rawName: "EquipmentHats67", name: "Acorn_Topper" },
  { rawName: "EquipmentHats75", name: "Apple_Launch_Hat" },
  { rawName: "EquipmentHats76", name: "Funny_Hat" },
  { rawName: "EquipmentHats78", name: "Meteorhead" },
  { rawName: "EquipmentHats79", name: "Ice_Guard_Helmet" },
  { rawName: "EquipmentHats31", name: "Smitty's_Bubble_Blowing_Hat" },
  { rawName: "EquipmentHats32", name: "Bandit_Bob_Mask" },
  { rawName: "EquipmentHats33", name: "Paper_Bag" },
  { rawName: "EquipmentHats34", name: "Parasite" },
  { rawName: "EquipmentHats35", name: "Diamond_Horns" },
  { rawName: "EquipmentHats36", name: "Halloween_Pumpkin" },
  { rawName: "EquipmentHats40", name: "Pardoned_Turkey" },
  { rawName: "EquipmentHats37", name: "Hotdog_Hero" },
  { rawName: "EquipmentHats38", name: "Invisible_Hat" },
  { rawName: "EquipmentHats46", name: "Strawbiggy" },
  { rawName: "EquipmentHats47", name: "Pop_Cat" },
  { rawName: "EquipmentHats48", name: "Dairy_Dunk" },
  { rawName: "EquipmentHats49", name: "The_Classic" },
  { rawName: "EquipmentHats50", name: "Green_Beanie" },
  { rawName: "EquipmentHats43", name: "Snowman" },
  { rawName: "EquipmentHats45", name: "Giftmas_Tree" },
  { rawName: "EquipmentHats57", name: "Big_Bunny" },
  { rawName: "EquipmentHats62", name: "Fluffy_Ramsy" },
  { rawName: "EquipmentHats65", name: "The_Red_Boaty" },
  { rawName: "EquipmentHats69", name: "Giftmas_Snoozy_Cap" },
  { rawName: "EquipmentHats80", name: "Corgi_Topper" },
  { rawName: "EquipmentHats109", name: "Husky_Hat" },
  { rawName: "EquipmentHats81", name: "Siege_Captain_Cap" },
  { rawName: "EquipmentHats82", name: "Ele_Sorcerer_Pointed_Hat" },
  { rawName: "EquipmentHats85", name: "Bedsheet_with_Holes" },
  { rawName: "EquipmentHats86", name: "Carrotman_Mask" },
  { rawName: "EquipmentHats87", name: "Glublin_Mask" },
  { rawName: "EquipmentHats88", name: "Bloque_Mask" },
  { rawName: "EquipmentHats89", name: "Borzoi_Topper" },
  { rawName: "EquipmentHats90", name: "Straw_Hat" },
  { rawName: "EquipmentHats91", name: "Wig_Bandana" },
  { rawName: "EquipmentHats92", name: "Funky_Hat" },
  { rawName: "EquipmentHats93", name: "Reinforced_Headband" },
  { rawName: "EquipmentHats94", name: "Shogun_Helmet" },
  { rawName: "EquipmentHats95", name: "Gilded_Headband" },
  { rawName: "EquipmentHats96", name: "Bamboo_Hat" },
  { rawName: "EquipmentHats97", name: "Festive_Beast_Mask" },
  { rawName: "EquipmentHats98", name: "Heiress_Headdress" },
  { rawName: "EquipmentHats99", name: "Spirited_Mane" },
  { rawName: "EquipmentHats100", name: "Fiery_Mane" },
  { rawName: "EquipmentHats101", name: "Guardian_Mane" },
  { rawName: "EquipmentHats102", name: "Fanned_Blossomage" },
  { rawName: "EquipmentHats103", name: "Dainty_Brim" },
  { rawName: "EquipmentHats104", name: "Charcoal_Hat" },
  { rawName: "EquipmentHats110", name: "Yellow_Beanie" },
  { rawName: "EquipmentHats112", name: "Deathbringer_Hood_of_Death" },
  { rawName: "EquipmentHats113", name: "Pink_Beanie" },
  { rawName: "EquipmentHats114", name: "True_Crown" },
  { rawName: "EquipmentHats115", name: "Celebration_Mane" },
  { rawName: "EquipmentHats116", name: "Goldberry" },
  { rawName: "EquipmentHats117", name: "Orange_Beanie" },
  { rawName: "EquipmentHats118", name: "Windwalker_Hood" },
  { rawName: "EquipmentHats120", name: "Umbrella_Brim" },
  { rawName: "EquipmentHats121", name: "Bloo_Creamer" },
  { rawName: "EquipmentHats122", name: "Arcanist_Crown" },
  { rawName: "EquipmentHats124", name: "Alpine_Beanie" },
  { rawName: "EquipmentHats125", name: "Rudolph_Antlers" },
  { rawName: "EquipmentHats126", name: "Helper_Elf_Hat" },
  { rawName: "EquipmentHats127", name: "Seal_Team_Skipper_Hat" },
  { rawName: "EquipmentHats128", name: "Lovely_Top_Hat" },
  { rawName: "EquipmentHats129", name: "Polkadot_Beanie" },
  { rawName: "EquipmentHats130", name: "Leprechaun_Hat" },
  { rawName: "EquipmentHats131", name: "Lucky_Ducky_Brim" },
  { rawName: "EquipmentHats132", name: "Time_Traveler_Top_Hat" },
  { rawName: "EquipmentHats133", name: "Native_Headdress" },
  { rawName: "EquipmentHats134", name: "Starry_Hairpins" },
  { rawName: "EquipmentHats135", name: "Blonde_Hairpiece" },
  { rawName: "EquipmentHats139", name: "Sun_Hat" }
];

export const TROPHIES: NamedRaw[] = [
  { rawName: "Trophy1", name: "King_of_Food" },
  { rawName: "Trophy2", name: "Lucky_Lad" },
  { rawName: "Trophy3", name: "Club_Member" },
  { rawName: "Trophy4", name: "I_Made_This_Game" },
  { rawName: "Trophy5", name: "Dice_Dynamo" },
  { rawName: "Trophy6", name: "Blunder_Hero" },
  { rawName: "Trophy7", name: "Original_Gamer" },
  { rawName: "Trophy8", name: "Trailblazer" },
  { rawName: "Trophy9", name: "Ultra_Unboxer" },
  { rawName: "Trophy10", name: "Critter_Baron" },
  { rawName: "Trophy11", name: "YumYum_Sheriff" },
  { rawName: "Trophy12", name: "Megalodon" },
  { rawName: "Trophy13", name: "Club_Maestro" },
  { rawName: "Trophy14", name: "Beach_Bro" },
  { rawName: "Trophy15", name: "Frost_Prince" },
  { rawName: "Trophy16", name: "Idle_Skiller" },
  { rawName: "Trophy17", name: "One_of_the_Divine" },
  { rawName: "Trophy18", name: "Master_of_Nothing" },
  { rawName: "Trophy19", name: "Nebula_Royal" },
  { rawName: "Trophy20", name: "Luckier_Lad" },
  { rawName: "Trophy21", name: "Baller" },
  { rawName: "Trophy22", name: "Gladiator" },
  { rawName: "Trophy23", name: "Heroic_Spirit" },
  { rawName: "Trophy24", name: "Nine_Dart_Finish" },
  { rawName: "Trophy25", name: "Luckiest_Lad" }
];

export const NAMETAGS: NamedRaw[] = [
  { rawName: "EquipmentNametag1", name: "Riftwalker_Nametag" },
  { rawName: "EquipmentNametag2", name: "Lava's_Awesome_Nametag" },
  { rawName: "EquipmentNametag3", name: "Balling_Nametag" },
  { rawName: "EquipmentNametag4", name: "Vman_Nametag" },
  { rawName: "EquipmentNametag5", name: "Spring_Flowers_Nametag" },
  { rawName: "EquipmentNametag6b", name: "Trash_Tuna_Nametag" },
  { rawName: "EquipmentNametag7", name: "Island_Adventurer_Nametag" },
  { rawName: "EquipmentNametag8", name: "Summer_Shovel_Nametag" },
  { rawName: "EquipmentNametag9", name: "Falloween_Nametag" },
  { rawName: "EquipmentNametag10", name: "3rd_Anniversary_IdleOn_Nametag" },
  { rawName: "EquipmentNametag11", name: "Nightshade_Nametag" },
  { rawName: "EquipmentNametag12", name: "Megafeather_Nametag" },
  { rawName: "EquipmentNametag13", name: "Timeless_Nametag" },
  { rawName: "EquipmentNametag14", name: "Snowflake_Nametag" },
  { rawName: "EquipmentNametag15", name: "Frostyman_Nametag" },
  { rawName: "EquipmentNametag16", name: "Lovely_Day_Nametag" },
  { rawName: "EquipmentNametag17", name: "Spectacular_4th_Year_Nametag" },
  { rawName: "EquipmentNametag18", name: "4th_Anniversary_IdleOn_Nametag" },
  { rawName: "EquipmentNametag19", name: "Aethermoon_Nametag" },
  { rawName: "EquipmentNametag20", name: "Deadbones_Nametag" },
  { rawName: "EquipmentNametag21", name: "Treasure_Nametag" },
  { rawName: "EquipmentNametag22", name: "Tome_Apprentice_Nametag" },
  { rawName: "EquipmentNametag23", name: "Tome_Journeyman_Nametag" },
  { rawName: "EquipmentNametag24", name: "Tome_Expert_Nametag" },
  { rawName: "EquipmentNametag25", name: "Tome_Elite_Nametag" },
  { rawName: "EquipmentNametag26", name: "Tome_Pro_Nametag" },
  { rawName: "EquipmentNametag27", name: "Tome_Master_Nametag" },
  { rawName: "EquipmentNametag28", name: "Tome_Legend_Nametag" },
  { rawName: "EquipmentNametag29", name: "Reliquarium_Nametag" },
  { rawName: "EquipmentNametag30", name: "Cropfall_Nametag" },
  { rawName: "EquipmentNametag31", name: "Gingerbread_Nametag" },
  { rawName: "EquipmentNametag32", name: "Sweet_Chocolate_Nametag" },
  { rawName: "EquipmentNametag33", name: "Pot_of_Gold_Nametag" },
  { rawName: "EquipmentNametag34", name: "Emerald_Nametag" },
  { rawName: "EquipmentNametag35", name: "5th_Anniversary_IdleOn_Nametag" },
  { rawName: "EquipmentNametag36", name: "Wonderful_5th_Year_Nametag" },
  { rawName: "EquipmentNametag37", name: "Grand_Egg_Nametag" },
  { rawName: "EquipmentNametag41", name: "All_That_Glitters_Nametag" }
];

export const TOWER_BONUS_INC: number[] = [1, 1.18, 1.23, 2, 1.27, 1.106, 1.95, 4, 1.14, 1.365, 1.33, 1.276, 1.246, 1.23, 1.222, 1.22, 1.21, 1.4, 1.16, 1.15, 1.13, 1.115, 1.11, 1.106, 1.106, 1.1, 1.09];
export const BUILD_COST_MULTIPLIER: number[] = [3, 200, 2250, 12000, 25000, 60000, 100000, 150000, 50000000, 5, 100, 700, 5000, 40000, 125000, 400000, 1000000, 3500000, 10, 250, 1000, 7500, 40000, 200000, 2000000, 7000000, 60000000];
export const REFINERY_POWER_CAPS: number[] = [50, 50, 200, 800, 3000, 8000, 14000, 20000, 30000, 40000, 50000, 65000, 80000, 100000, 200000, 300000, 400000, 500000, 600000, 700000, 800000, 900000, 1000000, 1000000, 1000000, 1000000];

export const REFINERY_SALT_INFO: RefinerySaltInfo[] = [
  { rawName: "Refinery1", saltName: "Redox_Salts", cost: [{ rawName: "Grasslands1", quantity: 10 }, { rawName: "Copper", quantity: 5 }] },
  { rawName: "Refinery2", saltName: "Explosive_Salts", cost: [{ rawName: "Forest3", quantity: 10 }, { rawName: "ForestTree", quantity: 5 }, { rawName: "Refinery1", quantity: 2 }] },
  { rawName: "Refinery3", saltName: "Spontaneity_Salts", cost: [{ rawName: "DesertA1", quantity: 50 }, { rawName: "Fish1", quantity: 30 }, { rawName: "Bug1", quantity: 40 }, { rawName: "Refinery2", quantity: 2 }] },
  { rawName: "Refinery4", saltName: "Dioxide_Synthesis", cost: [{ rawName: "SnowA1", quantity: 10 }, { rawName: "Soul2", quantity: 2 }, { rawName: "Critter3", quantity: 1 }, { rawName: "Refinery3", quantity: 1 }] },
  { rawName: "Refinery5", saltName: "Purple_Salt", cost: [{ rawName: "SnowB4", quantity: 25 }, { rawName: "Fish4", quantity: 5 }, { rawName: "Bug3", quantity: 5 }, { rawName: "Critter4", quantity: 5 }, { rawName: "Refinery4", quantity: 2 }] },
  { rawName: "Refinery6", saltName: "Nullo_Salt", cost: [{ rawName: "SnowC4", quantity: 50 }, { rawName: "VoidBar", quantity: 5 }, { rawName: "Tree7", quantity: 5 }, { rawName: "Bug6", quantity: 5 }, { rawName: "Soul4", quantity: 5 }, { rawName: "Refinery5", quantity: 2 }] },
  { rawName: "Refinery7", saltName: "Crosslink_Salt", cost: [{ rawName: "SpiB2", quantity: 10 }, { rawName: "Soul7", quantity: 2 }, { rawName: "Critter11", quantity: 1 }, { rawName: "Refinery6", quantity: 1 }] },
  { rawName: "Refinery8", saltName: "Propagated_Salt", cost: [{ rawName: "w7A1", quantity: 25 }, { rawName: "Fish12", quantity: 5 }, { rawName: "Bug15", quantity: 5 }, { rawName: "PrehistriumBar", quantity: 5 }, { rawName: "Refinery7", quantity: 2 }] },
  { rawName: "Refinery9", saltName: "Anionic_Salt", cost: [{ rawName: "w7B10", quantity: 50 }, { rawName: "FillerMaterial", quantity: 5 }, { rawName: "FillerMaterial", quantity: 5 }, { rawName: "FillerMaterial", quantity: 5 }, { rawName: "Soul8", quantity: 5 }, { rawName: "Refinery8", quantity: 2 }] }
];

export const SIGIL_INFO: SigilInfo[] = [
  { name: "BIG_MUSCLE", boostCost: 100, jadeCost: 50000, etherealCost: 250000, eclecticCost: 10000000 },
  { name: "PUMPED_KICKS", boostCost: 150, jadeCost: 60000, etherealCost: 300000, eclecticCost: 20000000 },
  { name: "ODD_LITEARTURE", boostCost: 200, jadeCost: 70000, etherealCost: 400000, eclecticCost: 30000000 },
  { name: "GOOD_FORTUNE", boostCost: 300, jadeCost: 90000, etherealCost: 500000, eclecticCost: 50000000 },
  { name: "PLUNGING_SWORD", boostCost: 700, jadeCost: 100000, etherealCost: 600000, eclecticCost: 60000000 },
  { name: "WIZARDLY_HAT", boostCost: 1250, jadeCost: 130000, etherealCost: 700000, eclecticCost: 100000000 },
  { name: "ENVELOPE_PILE", boostCost: 2500, jadeCost: 160000, etherealCost: 1000000, eclecticCost: 250000000 },
  { name: "SHINY_BEACON", boostCost: 4000, jadeCost: 200000, etherealCost: 1400000, eclecticCost: 70000000 },
  { name: "METAL_EXTERIOR", boostCost: 7000, jadeCost: 240000, etherealCost: 1700000, eclecticCost: 200000000 },
  { name: "TWO_STARZ", boostCost: 10000, jadeCost: 280000, etherealCost: 2200000, eclecticCost: 300000000 },
  { name: "PIPE_GAUGE", boostCost: 12000, jadeCost: 320000, etherealCost: 2600000, eclecticCost: 600000000 },
  { name: "TROVE", boostCost: 14000, jadeCost: 400000, etherealCost: 3000000, eclecticCost: 1250000000 },
  { name: "PEA_POD", boostCost: 15000, jadeCost: 420000, etherealCost: 3500000, eclecticCost: 2500000000 },
  { name: "TUFT_OF_HAIR", boostCost: 25000, jadeCost: 450000, etherealCost: 4300000, eclecticCost: 6000000000 },
  { name: "EMOJI_VEGGIE", boostCost: 33000, jadeCost: 480000, etherealCost: 5500000, eclecticCost: 12000000000 },
  { name: "VIP_PARCHMENT", boostCost: 42000, jadeCost: 520000, etherealCost: 6700000, eclecticCost: 25000000000 },
  { name: "DREAM_CATCHER", boostCost: 50000, jadeCost: 560000, etherealCost: 8200000, eclecticCost: 40000000000 },
  { name: "DUSTER_STUDS", boostCost: 60000, jadeCost: 600000, etherealCost: 10000000, eclecticCost: 60000000000 },
  { name: "GARLIC_GLOVE", boostCost: 70000, jadeCost: 650000, etherealCost: 12000000, eclecticCost: 100000000000 },
  { name: "LAB_TESSTUBE", boostCost: 80000, jadeCost: 700000, etherealCost: 14000000, eclecticCost: 200000000000 },
  { name: "PECULIAR_VIAL", boostCost: 120000, jadeCost: 750000, etherealCost: 15000000, eclecticCost: 350000000000 },
  { name: "LOOT_PILE", boostCost: 160000, jadeCost: 900000, etherealCost: 16000000, eclecticCost: 500000000000 },
  { name: "DIV_SPIRAL", boostCost: 200000, jadeCost: 1200000, etherealCost: 17000000, eclecticCost: 700000000000 },
  { name: "COOL_COIN", boostCost: 250000, jadeCost: 2000000, etherealCost: 20000000, eclecticCost: 1000000000000 }
];

export const POPPY_UPGRADES: PoppyUpgrade[] = [
  { name: "tasty_Fishbait", x1: 4, x2: 1.06, x3: 100 },
  { name: "Quick_Reeling", x1: 150, x2: 1.2, x3: 500 },
  { name: "Shiny_Lure", x1: 500, x2: 3.5, x3: 2500 },
  { name: "Bonuses_from_Poppy", x1: 10000, x2: 3, x3: 30000 },
  { name: "fishy_discount", x1: 30000, x2: 1.13, x3: 250000 },
  { name: "Juicy_Worm", x1: 150000, x2: 1.07, x3: 3000000 },
  { name: "Fisheroo_Reset", x1: 40000000, x2: 20, x3: 25000000 },
  { name: "Fishing_Buddy", x1: 1200000000, x2: 7.5, x3: 600000000 },
  { name: "Lightning_Quickness", x1: 600000000, x2: 1.12, x3: 4000000000 },
  { name: "Fisheroo_Investing", x1: 7500000000, x2: 1.7, x3: 14000000000 },
  { name: "Multihook_Fishing", x1: 20000000000, x2: 1.12, x3: 80000000000 },
  { name: "Greatest_Catch", x1: 1500000000000, x2: 15, x3: 400000000000 }
];

export const VILLAGER_NAMES = ['Explorer', 'Engineer', 'Bonuses', 'Measure', 'Studies'] as const;
export const STUDY_NAMES = ["THE_WELL", "MOTHERLODE", "THE_DEN", "BRAVERY", "THE_BELL", "THE_HARP", "THE_LAMP", "THE_HIVE", "GROTTO", "JUSTICE", "THE_JARS", "EVERTREE", "WISDOM", "GAMBIT", "TEMPLE", "FOUNTAIN", "TRENCH", "THE_COVE", "BRUH", "BRUH"] as const;

export const DEFAULT_MEAL_MAX_LEVEL = 110;

export const ARCADE_EFFECTS = [
  "+{_Base_Damage",
  "+{_Base_Defence",
  "+{%_Total_Accuracy",
  "+{%_Mining_EXP_gain",
  "+{%_Fishing_EXP_gain",
  "+{%_Sample_Size",
  "+{%_AFK_Gains_Rate",
  "+{_Cap_for_all_Liquids",
  "+{%_Multikill_per_Tier",
  "+{%_Catching_EXP_gain",
  "+{%_Cash_from_Mobs",
  "+{%_Cash_from_Mobs",
  "+{%_Class_EXP_gain",
  "+{%_Shiny_Chance",
  "+{%_Trapping_EXP",
  "+{_Starting_TD_Pts",
  "+{_Tab_1_Talent_Pt",
  "+{_Weapon_Power",
  "+{%_Skill_EXP_gain",
  "+{_Base_STR",
  "+{_Base_AGI",
  "+{_Base_WIS",
  "+{_Base_LUK",
  "+{%_Trapping_Critters",
  "+{%_Worship_Souls",
  "+{%_Refinery_Speed",
  "+{%_Forge_Capacity",
  "+{%_Drop_Rate",
  "+{%_Cook_SPD_multi",
  "+{%_Lab_EXP_gain",
  "+{%_Breed_Mob_DMG",
  "+{%_Nugget_Regen",
  "+{%_Artifact_Find",
  "+{%_Sailing_Loot",
  "+{%_W_Ess_gain",
  "+{%_Jade_gain",
  "+{%_Farming_EXP",
  "+{%_Divinity_EXP",
  "+{%_Villager_XP_multi",
  "+{%_Gold_Ball_Gain",
  "+{%_Deathbringer_Bones",
  "+{%_Equinox_Fill_Rate",
  "+{%_Monument_AFK",
  "+{%_Sigil_Speed",
  "+{%_Construction_Build",
  "+{%_Burger",
  "+{%_Total_Damage",
  "+{%_Windwalker_Dust",
  "+{%_Medallion_Chance",
  "+{%_Breedability_Rate",
  "+{%_Arcane_Tachyons",
  "+{%_Emperor_Bonuses",
  "+{%_Sneaking_XP_multi",
  "+{%_Summon_XP_multi",
  "+{%_Prisma_Bonuses",
  "+{%_Spelunking_Amber",
  "+{%_Spelunk_XP_multi",
  "+{%_Daily_Coral",
  "+{%_Palette_Luck",
  "+{%_Meritocracy_Bonus",
  "+{%_Class_XP_multi",
  "+{%_Kruk_Bubble_LVs",
  "+{%_Minehead_Currency",
  "+{%_Research_XP",
  "+{%_Megacrop_Chance",
  "+{%_New_Crown_Chance",
  "+{%_Artifact_Find",
  "+{%_Sushi_Bucks",
  "+{%_Fountain_Speed",
  "+{%_Cook_Mastery_EXP"
];

/** Max spendable legend talent levels (x1). Fillers 40–49 are 0. */
export const LEGEND_TALENT_MAX = [
  2, 4, 3, 3, 2, 5, 2, 5, 2, 2, 5, 4, 3, 4, 1, 2, 2, 2, 2, 2, 4, 5, 1, 3, 1, 3, 2, 3, 2, 2, 2, 3, 1, 2, 2, 1, 5, 1, 1, 1
];

export const LEGEND_COG_TALENT_INDEX = 18;
export const LEGEND_COG_TALENT_X2 = 2;
export const LEGEND_MASTERCLASS_TALENT_INDEX = 23;
export const LEGEND_MASTERCLASS_TALENT_X2 = 8;
export const JEWEL_COGS_SUPERBIT_INDEX = 33;
export const DOUBLE_CLUSTER_INDEX = 3;
export const DOUBLE_CLUSTER_X1 = 8;
export const DOUBLE_CLUSTER_X2 = 1.17;
export const DOUBLE_CLUSTER_MAX = 100;

export const RESEARCH_OCCURRENCE_NAMES = [
  "Bored_Tree",
  "Shopping_Oyseter",
  "Bridge_Plank",
  "Carrot_Patch",
  "Salty_Seawebs",
  "Dogbone_Tombstone",
  "Ominous_Signage",
  "Canyon_Pointerino",
  "Corange_Coral",
  "Oasis_Erosion",
  "Barnacle_Brothers",
  "Green_Shallowrock",
  "Broken_Spacerocks",
  "Meenie_Cactus",
  "Coraltree_Branch",
  "Useless_Anchor",
  "Oboe_Coral_Trio",
  "Spadespire",
  "Seaswept_Ruins",
  "Tetrino_Stones",
  "Stalagtite",
  "OG_Secret_Rock",
  "Happy_Piggy",
  "Treeception",
  "Keymaster",
  "Space_Drip",
  "Coralcave_Coral",
  "Unblinking_Eye",
  "Monster_Decoy",
  "Standard_Stump",
  "Big_Ol_Reef",
  "Oasis_Palm",
  "Stalagmite",
  "Rope_Lamp",
  "Unremarkable_Rock",
  "Standard_Mine",
  "Ancient_Chainrope",
  "Birchtree_Bitty",
  "Unreachable_Grate",
  "Genuine_Deadwood",
  "Rifty_Crystals",
  "Pirate_Flag",
  "Happy_Tree"
];

export const SUSHI_NAMES = [
  "Fish_Eggs",
  "Eggroll",
  "Egg_Maki",
  "Sashimi",
  "Tuna_Maki",
  "Salmon_Uramaki",
  "Salmon_Maki",
  "Cucumber_Uramaki",
  "Cucumber_Maki",
  "Onigiri",
  "Toro_Slice",
  "Toro_Nigiri",
  "Beef_Nigiri",
  "Beef_Tobo_Nigiri",
  "Tobiko_Maki",
  "Tobiko_Temaki",
  "Tobiko_Cluster",
  "Tobo_Sardine",
  "Tobo_Twins",
  "Live_Squid",
  "Live_Octopus",
  "Calamari_Ring",
  "Bluefin_Ring",
  "Tobo_Tamago",
  "Tako_Sashimi",
  "Hamachi_Sashimi",
  "Fat_Tuna_Sashimi",
  "King_Beef_Sashimi",
  "Salmon_Sashimi",
  "Salmon_Nigiri",
  "Fried_Bass_Nigiri",
  "Seasoned_Bass_Nigiri",
  "Jumbo_Shrimp",
  "Aged_Shrimp_Nigiri",
  "Tempura_Shrimp",
  "Ika_Sashimi",
  "Abalone_Sashimi",
  "Aji_Sashimi",
  "Aji_Aji_Sashimi",
  "Bubba_Grand_Salmon",
  "Tobiko_Roll",
  "Spicy_Tuna_Roll",
  "Salmon_Uramajor",
  "Sesame_Salmon_Muramajor",
  "Dragon_Roll",
  "Imaginei_Dragonroll",
  "Dragon_Nigiri",
  "Tamago_Nigiri",
  "Unagi_Nigiri",
  "Soylent_Nigiri",
  "Masago",
  "Masago_Temaki",
  "Masagoroll",
  "Caviar_Supreme",
  "Dulce_Vitiri",
  "Wasabaisamarama",
  "Kraken_Roll",
  "Leviathan_Roll",
  "Golthulu_Roll"
];
