export const BRIBE_SETS: { world: string; names: string[] }[] = [
  { world: 'W1', names: ['Insider Trading', 'Tracking Chips', 'Mandatory Fire Sale', 'Sleeping On the Job', 'Artificial Demand', 'The Art of the Deal'] },
  { world: 'W2', names: ['Overstock Regulations', 'Double EXP Scheme', 'Tagged Indicators', 'Fossil Fuel Legislation', 'Five Aces in the Deck', 'Fake Teleport Tickets', 'The Art of the Steal'] },
  { world: 'W3', names: ['Counterfeit Telepassports', 'Weighted Marbles', 'Changing the Code', 'Taxidermied Cog Pouches', 'Guild VIP Fraud', 'Library Double Agent', 'The Art of the Fail'] },
  { world: 'W4', names: ['Photoshopped Dmg Range', 'Glitched Acc Formula', 'Firewalled Defence', 'Bottomless Bags', 'AFKeylogging', 'Guild GP Hack'] },
  { world: 'Trash Island', names: ['The Art of the Bail', 'Random Garbage', 'Godlier Creation', 'Fishermaster', 'Muscles on Muscles', 'Bottle Service', 'Star Scraper'] },
  { world: 'W6', names: ['The Art of the Grail', 'Artifact Pilfering', 'Forge Cap Smuggling', 'Gold from Lead', 'Nugget Fabrication', 'Divine PTS Miscounting', 'Loot Table Tampering', 'The Art of the Flail'] }
];

/** Placeholder expansion bribes that the vendor will not sell yet. */
export const UNPURCHASABLE_BRIBES = new Set(['The Art of the Flail']);

export const STATUE_NAMES = [
  'Power',
  'Speed',
  'Mining',
  'Feasty',
  'Health',
  'Kachow',
  'Lumberbob',
  'Thicc Skin',
  'Oceanman',
  'Ol Reliable',
  'Exp',
  'Anvil',
  'Cauldron',
  'Beholder',
  'Bullseye',
  'Box',
  'Twosoul',
  'Ehexpee',
  'Seesaw',
  'Pecunia',
  'Mutton',
  'Egg',
  'Battleaxe',
  'Spiral',
  'Boat',
  'Compost',
  'Stealth',
  'Essence',
  'Villager',
  'Dragon',
  'Spelunky',
  'Coral'
];

export const STATUE_TYPES = ['Normal', 'Gold', 'Onyx', 'Zenith'] as const;

export const FORGE_UPGRADES = [
  { name: 'New Forge Slot', max: 16 },
  { name: 'Ore Capacity Boost', max: 50 },
  { name: 'Forge Speed', max: 90 },
  { name: 'Forge EXP Gain', max: 85 },
  { name: 'Bar Bonanza', max: 75 },
  { name: 'Puff Puff Go', max: 60 }
];

export const POST_OFFICE_BOXES = [
  'Civil War Memory Box',
  'Locally Sourced Organs',
  'Magician Starterpack',
  'Box of Unwanted Stats',
  'Dwarven Supplies',
  'Blacksmith Box',
  'Taped Up Timber',
  'Carepack From Mum',
  'Sealed Fishheads',
  'Potion Package',
  'Bug Hunting Supplies',
  'Non Predatory Loot Box',
  'Deaths Storage Unit',
  'Utilitarian Capsule',
  'Lazzzy Lootcrate',
  'Science Spare Parts',
  'Trapping Lockbox',
  'Construction Container',
  'Crate of the Creator',
  'Chefs Essentials',
  'Myriad Crate',
  'Box of Gosh',
  'Gaming Lootcrate'
];

export const CONSTRUCTION_BUILDINGS: { name: string; max: number; type: 'Utility' | 'Tower' | 'Shrine' }[] = [
  { name: '3D Printer', max: 10, type: 'Utility' },
  { name: 'Talent Book Library', max: 101, type: 'Utility' },
  { name: 'Death Note', max: 51, type: 'Utility' },
  { name: 'Salt Lick', max: 10, type: 'Utility' },
  { name: 'Chest Space', max: 25, type: 'Utility' },
  { name: 'Cost Cruncher', max: 60, type: 'Utility' },
  { name: 'Trapper Drone', max: 15, type: 'Utility' },
  { name: 'Automation Arm', max: 5, type: 'Utility' },
  { name: 'Atom Collider', max: 200, type: 'Utility' },
  { name: 'Pulse Mage', max: 50, type: 'Tower' },
  { name: 'Fireball Lobber', max: 50, type: 'Tower' },
  { name: 'Boulder Roller', max: 50, type: 'Tower' },
  { name: 'Frozone Malone', max: 50, type: 'Tower' },
  { name: 'Stormcaller', max: 50, type: 'Tower' },
  { name: 'Party Starter', max: 50, type: 'Tower' },
  { name: 'Kraken Cosplayer', max: 50, type: 'Tower' },
  { name: 'Poisonic Elder', max: 50, type: 'Tower' },
  { name: 'Voidinator', max: 50, type: 'Tower' },
  { name: 'Woodular Shrine', max: 100, type: 'Shrine' },
  { name: 'Isaccian Shrine', max: 100, type: 'Shrine' },
  { name: 'Crystal Shrine', max: 100, type: 'Shrine' },
  { name: 'Pantheon Shrine', max: 100, type: 'Shrine' },
  { name: 'Clover Shrine', max: 100, type: 'Shrine' },
  { name: 'Summereading Shrine', max: 100, type: 'Shrine' },
  { name: 'Crescent Shrine', max: 100, type: 'Shrine' },
  { name: 'Undead Shrine', max: 100, type: 'Shrine' },
  { name: 'Primordial Shrine', max: 100, type: 'Shrine' }
];

export const SALT_LICK_UPGRADES = [
  'Printer Sample Size',
  'Obol Storage',
  'Refinery Speed',
  'EXP',
  'Max Book',
  'Alchemy Liquids',
  'TD Points',
  'Movespeed',
  'Multikill',
  'Damage',
  'Cooking Mastery'
];

export const PRAYER_NAMES = [
  'Big Brain Time',
  'Skilled Dimwit',
  'Unending Energy',
  'Shiny Snitch',
  'Zerg Rushogen',
  'Tachion of the Titans',
  'Balance of Precision',
  'Midas Minded',
  'Jawbreaker',
  'The Royal Sampler',
  'Antifun Spirit',
  'Circular Criticals',
  'Ruck Sack',
  'Fibers of Absence',
  'Vacuous Tissue',
  'Beefy For Real',
  'Balance of Pain',
  'Balance of Proficiency',
  'Glitterbug'
];

export const WORSHIP_TOTEMS = [
  'Goblin Gorefest',
  'Wakawaka War',
  'Acorn Assault',
  'Frosty Firefight',
  'Clash of Cans',
  'Citric Conflict',
  'Breezy Battle'
];

export const REFINERY_SALTS: { name: string; index: number }[] = [
  { name: 'Redox', index: 3 },
  { name: 'Explosive', index: 4 },
  { name: 'Spontaneity', index: 5 },
  { name: 'Dioxide', index: 6 },
  { name: 'Purple', index: 7 },
  { name: 'Nullo', index: 8 }
];

export const DEATH_NOTE_SKULLS = [
  { name: 'None', kills: 0 },
  { name: 'Normal Skull', kills: 25_000 },
  { name: 'Copper Skull', kills: 100_000 },
  { name: 'Iron Skull', kills: 250_000 },
  { name: 'Gold Skull', kills: 500_000 },
  { name: 'Platinum Skull', kills: 1_000_000 },
  { name: 'Dementia Skull', kills: 5_000_000 },
  { name: 'Lava Skull', kills: 100_000_000 },
  { name: 'Eclipse Skull', kills: 1_000_000_000 }
];

/** Regular Death Note monster maps only (no colosseum, bosses, dungeons, or skill maps). */
export const DEATH_NOTE_MAPS: { world: number; mapId: number; portalReq: number }[] = [
  { world: 1, mapId: 1, portalReq: 11 },
  { world: 1, mapId: 2, portalReq: 15 },
  { world: 1, mapId: 8, portalReq: 20_000 },
  { world: 1, mapId: 13, portalReq: 2_500 },
  { world: 1, mapId: 14, portalReq: 40 },
  { world: 1, mapId: 15, portalReq: 35_000 },
  { world: 1, mapId: 16, portalReq: 60 },
  { world: 1, mapId: 17, portalReq: 0 },
  { world: 1, mapId: 18, portalReq: 5_000 },
  { world: 1, mapId: 19, portalReq: 125 },
  { world: 1, mapId: 24, portalReq: 100 },
  { world: 1, mapId: 26, portalReq: 150 },
  { world: 1, mapId: 27, portalReq: 30 },
  { world: 1, mapId: 28, portalReq: 0 },
  { world: 1, mapId: 31, portalReq: 0 },
  { world: 2, mapId: 51, portalReq: 250 },
  { world: 2, mapId: 52, portalReq: 600 },
  { world: 2, mapId: 53, portalReq: 1_000 },
  { world: 2, mapId: 57, portalReq: 1_200 },
  { world: 2, mapId: 58, portalReq: 1_600 },
  { world: 2, mapId: 59, portalReq: 2_000 },
  { world: 2, mapId: 60, portalReq: 2_500 },
  { world: 2, mapId: 62, portalReq: 3_000 },
  { world: 2, mapId: 63, portalReq: 4_000 },
  { world: 2, mapId: 64, portalReq: 5_000 },
  { world: 2, mapId: 65, portalReq: 1 },
  { world: 3, mapId: 101, portalReq: 1_000 },
  { world: 3, mapId: 103, portalReq: 2_000 },
  { world: 3, mapId: 104, portalReq: 3_000 },
  { world: 3, mapId: 105, portalReq: 4_000 },
  { world: 3, mapId: 106, portalReq: 6_000 },
  { world: 3, mapId: 107, portalReq: 8_000 },
  { world: 3, mapId: 108, portalReq: 11_000 },
  { world: 3, mapId: 109, portalReq: 15_000 },
  { world: 3, mapId: 110, portalReq: 18_000 },
  { world: 3, mapId: 111, portalReq: 22_000 },
  { world: 3, mapId: 112, portalReq: 35_000 },
  { world: 3, mapId: 113, portalReq: 120_000 },
  { world: 3, mapId: 116, portalReq: 250_000 },
  { world: 3, mapId: 117, portalReq: 0 },
  { world: 4, mapId: 151, portalReq: 5_000 },
  { world: 4, mapId: 152, portalReq: 12_000 },
  { world: 4, mapId: 153, portalReq: 18_000 },
  { world: 4, mapId: 154, portalReq: 25_000 },
  { world: 4, mapId: 155, portalReq: 40_000 },
  { world: 4, mapId: 156, portalReq: 60_000 },
  { world: 4, mapId: 157, portalReq: 90_000 },
  { world: 4, mapId: 158, portalReq: 120_000 },
  { world: 4, mapId: 159, portalReq: 150_000 },
  { world: 4, mapId: 160, portalReq: 190_000 },
  { world: 4, mapId: 161, portalReq: 250_000 },
  { world: 4, mapId: 162, portalReq: 300_000 },
  { world: 4, mapId: 163, portalReq: 350_000 },
  { world: 5, mapId: 201, portalReq: 15_000 },
  { world: 5, mapId: 202, portalReq: 25_000 },
  { world: 5, mapId: 203, portalReq: 40_000 },
  { world: 5, mapId: 204, portalReq: 50_000 },
  { world: 5, mapId: 205, portalReq: 75_000 },
  { world: 5, mapId: 206, portalReq: 100_000 },
  { world: 5, mapId: 207, portalReq: 200_000 },
  { world: 5, mapId: 208, portalReq: 300_000 },
  { world: 5, mapId: 209, portalReq: 450_000 },
  { world: 5, mapId: 210, portalReq: 600_000 },
  { world: 5, mapId: 211, portalReq: 1_000_000 },
  { world: 5, mapId: 212, portalReq: 3_000_000 },
  { world: 5, mapId: 213, portalReq: 60_000 },
  { world: 6, mapId: 251, portalReq: 30_000 },
  { world: 6, mapId: 252, portalReq: 50_000 },
  { world: 6, mapId: 253, portalReq: 100_000 },
  { world: 6, mapId: 254, portalReq: 250_000 },
  { world: 6, mapId: 255, portalReq: 400_000 },
  { world: 6, mapId: 256, portalReq: 1_100_000 },
  { world: 6, mapId: 257, portalReq: 3_200_000 },
  { world: 6, mapId: 258, portalReq: 8_000_000 },
  { world: 6, mapId: 259, portalReq: 12_000_000 },
  { world: 6, mapId: 260, portalReq: 25_000_000 },
  { world: 6, mapId: 261, portalReq: 70_000_000 },
  { world: 6, mapId: 262, portalReq: 100_000_000 },
  { world: 6, mapId: 263, portalReq: 150_000_000 },
  { world: 6, mapId: 264, portalReq: 100 },
  { world: 7, mapId: 301, portalReq: 100_000 },
  { world: 7, mapId: 302, portalReq: 250_000 },
  { world: 7, mapId: 303, portalReq: 10_000_000 },
  { world: 7, mapId: 304, portalReq: 5_000_000 },
  { world: 7, mapId: 305, portalReq: 20_000_000 },
  { world: 7, mapId: 306, portalReq: 0 },
  { world: 7, mapId: 307, portalReq: 250_000_000 },
  { world: 7, mapId: 308, portalReq: 60_000_000 },
  { world: 7, mapId: 309, portalReq: 0 },
  { world: 7, mapId: 310, portalReq: 500_000_000 },
  { world: 7, mapId: 311, portalReq: 1_000_000_000 },
  { world: 7, mapId: 312, portalReq: 0 },
  { world: 7, mapId: 315, portalReq: 2_000_000 },
  { world: 7, mapId: 316, portalReq: 6_000_000 },
  { world: 7, mapId: 317, portalReq: 1_000_000_000 },
  { world: 7, mapId: 318, portalReq: 60_000_000 },
  { world: 7, mapId: 319, portalReq: 125_000_000 },
  { world: 7, mapId: 320, portalReq: 250_000_000 },
  { world: 7, mapId: 321, portalReq: 350_000_000 },
  { world: 7, mapId: 322, portalReq: 500_000_000 },
  { world: 7, mapId: 325, portalReq: 2_000_000_000 },
  { world: 7, mapId: 326, portalReq: 0 }
];

export const ISLAND_CODES: { name: string; code: string }[] = [
  { name: 'Trash Island', code: '_' },
  { name: 'Rando Island', code: 'a' },
  { name: 'Crystal Island', code: 'b' },
  { name: 'Seasalt Island', code: 'c' },
  { name: 'Shimmer Island', code: 'd' },
  { name: 'Fractal Island', code: 'e' }
];

export const ATOM_NAMES = [
  'Hydrogen',
  'Helium',
  'Lithium',
  'Beryllium',
  'Boron',
  'Carbon',
  'Nitrogen',
  'Oxygen',
  'Fluoride',
  'Neon',
  'Sodium',
  'Magnesium',
  'Aluminium'
];

/** Indices 33–34 on each cauldron are unreleased filler “BUBBLE” slots. */
export const REAL_BUBBLES_PER_CAULDRON = 33;

export const COMPANION_NAMES = [
  "King Doot",
  "Rift Slug",
  "Dedotated Ram",
  "Crystal Custard",
  "Sheepie",
  "Molti",
  "Bored Bean",
  "Slime",
  "Sandy Pot",
  "Bloque",
  "Frog",
  "Glunko Supreme",
  "Ancient Golem",
  "Samurai Guardian",
  "Rift Jocund",
  "Leek Spirit",
  "Crystal Capybara",
  "Biggole Mole",
  "Gigafrog",
  "Mashed Potato",
  "Flying Worm",
  "Poisonic Frog",
  "Quenchie",
  "Green Mushroom",
  "Cool Bird",
  "Axolotl",
  "Mallay",
  "Spirit Reindeer",
  "RIP Tide",
  "Squirrel",
  "Mr Pig",
  "Wild Boar",
  "Whale",
  "Chippy",
  "Bunny",
  "Panda",
  "Hedgehog",
  "Whallamus",
  "Balloonfish",
  "Pufferblob",
  "Shellslug",
  "Crystal Cuttlefish",
  "Eamsy Earl",
  "Litterfish",
  "Spearfish",
  "Equinox Broadbass",
  "Mafioso",
  "Baby Boa",
  "Purp Mushroom",
  "Bubba the Seal",
  "Santa Snake",
  "Santas Little Helper",
  "Jellofish",
  "Koi Fish",
  "Neonscale",
  "Pirate Deckhand",
  "Magni Pufferfin",
  "Dreadnaught Captain",
  "Bubba Supreme",
  "Nutto",
  "Biggie Hours",
  "Baba Yaga",
  "Walking Stick",
  "Carrotman",
  "Demon Hound",
  "Gloomie Mushroom",
  "Crabcake",
  "Mr Blueberry",
  "Crystal Carrot",
  "Crystal Crabal",
  "Crystal Cattle",
  "Crystal Candalight",
  "Demon Genie",
  "Eldritch Croaker",
  "Lava Slimer",
  "King Frog",
  "Ghost",
  "Glublin",
  "Mamooth",
  "Mimic",
  "Moonmoon",
  "Red Mushroom",
  "Wood Mushroom",
  "Pincermin",
  "Wode Board",
  "Crescent Spud",
  "Rat",
  "Rift Spooker",
  "Rift Hivemind",
  "Floofie",
  "Sand Castle",
  "Sand Giant",
  "Dig Doug",
  "Xylobone",
  "Bloodbone",
  "Glunko The Massive",
  "Snelbie",
  "Cryosnake",
  "Shell Snake",
  "Snowman",
  "Bop Box",
  "Tyson",
  "Beefie",
  "Thermister",
  "TV",
  "Donut",
  "Soda Can",
  "Gelatinous Cuboid",
  "Choccie",
  "Clammie",
  "Octodar",
  "Flombeige",
  "Stilted Seeker",
  "Suggma",
  "Maccie",
  "Mister Brightside",
  "Cheese Nub",
  "Stiltmole",
  "Citringe",
  "Lampar",
  "Fire Spirit",
  "Crawler",
  "Tremor Wurm",
  "Sprout Spirit",
  "Ricecake",
  "River Spirit",
  "Baby Troll",
  "Woodlin Spirit",
  "Bamboo Spirit",
  "Lantern Spirit",
  "Mama Troll",
  "Ceramic Spirit",
  "Skydoggie Spirit",
  "Royal Egg",
  "Minichief Spirit",
  "Doodlefish",
  "Noble Clam",
  "Demonblub",
  "Coralcave Crab",
  "Coralcave Guardian",
  "Trench Fish",
  "Boomy Mine",
  "Pirate Underling",
  "Eggroll",
  "Kelpfish",
  "Mantaray",
  "Bronze Champion Ram",
  "Silver Champion Ram",
  "Gold Champion Ram",
  "Rift Stalker",
  "Glimbo",
  "Vanillie",
  "Valenslime",
  "Mechanical Mouse",
  "Lucky Slug",
  "Potluck",
  "Glunko The Massive",
  "Poppy",
  "Wickerlight Spirit",
  "Smoke Devil",
  "Bronze Champion Troll",
  "Silver Champion Troll",
  "Gold Champion Troll",
  "Abacus Frog",
  "Crystal Glunko",
  "Bin Goosey",
] as const;

/** Jade emporium index 22 = Crop Depot Scientist. Later indices are science pens. */
export const CROP_DEPOT_SCIENTIST_INDEX = 22;
export const CROP_DEPOT_SCIENCE_INDICES = [22, 23, 24, 25, 26, 27, 28, 29, 38, 40] as const;

