export type SkillLevels = Record<string, number>;

export type Character = {
  index: number;
  name: string;
  className: string;
  classId: number;
  combatLevel: number;
  currentMap: number;
  skills: SkillLevels;
  stats: { str: number; agi: number; wis: number; luk: number };
  postOfficeInvested: number;
  postOfficeBoxes: { name: string; level: number }[];
};

export type StampCategory = 'combat' | 'skills' | 'misc';

export type StampSummary = {
  category: StampCategory;
  index: number;
  level: number;
  maxLevel: number;
  delivered: boolean;
};

export type BubbleColor = 'orange' | 'green' | 'purple' | 'yellow';

export type BubbleSummary = {
  color: BubbleColor;
  index: number;
  level: number;
};

export type BribeStatus = -1 | 0 | 1;

export type BribeSummary = {
  set: string;
  name: string;
  status: BribeStatus;
};

export type StatueSummary = {
  index: number;
  name: string;
  level: number;
  type: string;
};

export type ForgeSummary = {
  name: string;
  purchased: number;
  max: number;
};

export type NamedLevel = {
  name: string;
  level: number;
  max?: number;
  extra?: string;
};

export type DeathNoteSummary = {
  mapsWithKills: number;
  goldSkulls: number;
  lavaSkulls: number;
  lowestSkull: string;
  lowestByWorld: { world: number; skull: string; maps: number }[];
};

export type ParsedAccount = {
  names: string[];
  characters: Character[];
  highestWorld: number;
  lastUpdatedMs: number | null;
  isStale: boolean;
  stamps: StampSummary[];
  stampLevels: number;
  stampsCollected: number;
  bubbles: BubbleSummary[];
  bubbleLevels: number;
  vials: number[];
  vialLevels: number;
  vialsUnlocked: number;
  bribes: BribeSummary[];
  bribesPurchased: number;
  statues: StatueSummary[];
  statueLevels: number;
  forge: ForgeSummary[];
  gemShopPurchases: number;
  cardsFound: number;
  achievements: number;
  postOfficeBoxesEarned: number;
  buildings: NamedLevel[];
  buildingsUnlocked: number;
  saltLick: NamedLevel[];
  prayers: NamedLevel[];
  prayersUnlocked: number;
  worshipTotems: NamedLevel[];
  worshipPeakWave: number;
  refinery: NamedLevel[];
  arcadeLevels: number;
  arcadeUpgrades: number;
  deathNote: DeathNoteSummary;
  mealsUnlocked: number;
  mealLevels: number;
  kitchensOwned: number;
  sigilsUnlocked: number;
  starSignsUnlocked: number;
  vaultLevels: number;
  vaultUpgrades: number;
  printerSamples: number;
  libraryBooks: number;
  atoms: NamedLevel[];
  atomsUnlocked: number;
  breedingPets: number;
  breedingArenaWave: number;
  breedingTerritory: number;
  labJewels: number;
  labChips: number;
  riftLevel: number;
  sailingIslands: number;
  sailingArtifacts: number;
  sailingArtifactTiers: number;
  sailingBoats: number;
  sailingCaptains: number;
  divinityGods: number;
  gamingBits: number;
  gamingSuperbits: number;
  slabItems: number;
  owlDiscovered: boolean;
  owlMegaFeathers: number;
  owlRestarts: number;
  islandsUnlocked: number;
  islandTrash: number;
  killroyFights: number;
  obolsOwned: number;
  equinoxDreams: number;
  equinoxBonusLevels: number;
  shrinesUnlocked: number;
  shrineLevels: number;
  farmCrops: number;
  farmPlots: number;
  farmMarketLevels: number;
  farmLandRanks: number;
  sneakingJadeUpgrades: number;
  sneakingNinjaLevels: number;
  sneakingPristineCharms: number;
  summonWins: number;
  summonUpgradeLevels: number;
  summonEndless: number;
  cavernsUnlocked: number;
  villagerLevels: number;
  cavernSchematics: number;
  coralUnlocked: number;
  cogsPlaced: number;
  flagsComplete: number;
  grimoireLevels: number;
  compassLevels: number;
  compassAbominations: number;
  compassMedallions: number;
  tesseractLevels: number;
  farmExoticLevels: number;
  researchCells: number;
  researchOccurrences: number;
  mineheadOpponents: number;
  mineheadUpgrades: number;
  legendTalents: number;
  companionDataPresent: boolean;
  companionsOwned: number;
  companionNames: string[];
  tomeBluePages: boolean;
  tomeRedPages: boolean;
  tomeTrackedScore: number;
  sushiSlots: number;
  sushiUnique: number;
  sushiUpgradeLevels: number;
  sushiFuel: number;
  sushiSparks: number;
  sushiBucks: number;
  buttonPresses: number;
  buttonInstaSkips: number;
  cropDepotScientist: boolean;
  cropDepotScience: number;
  magicBeanTrade: number;
  emperorShowdown: number;
  armorSmithyUnlocked: boolean;
  armorSetsUnlocked: number;
  armorSmithyDays: number;
  guildName?: string;
  ops: DashboardOps;
  source: 'cloud' | 'json';
  raw: Record<string, unknown>;
};

export type DashboardOps = {
  option: (index: number) => number;
  optionRaw: (index: number) => unknown;
  globalTimeSec: number;
  gildedStamps: number;
  randomEventDoneToday: boolean;
  bossGemKillsUsed: number;
  crystalKillsToday: number;
  tournamentDay: number;
  tournamentRegisteredThrough: number;
  petMartClaimDay: number;
  tournamentShopDay: number;
  killroyWeekProgress: number;
  killroyThirdRoom: boolean;
  killroySkulls: number;
  weeklyBossDone: boolean;
  alternateParticles: number;
  islandAfkDays: number;
  shimmerClaimed: boolean;
  islandTrash: number;
  garbageUpgradeLevel: number;
  bargainMultiplier: number;
  alchemyGemMultiplier: number;
  liquids: number[];
  vialAttempts: number;
  libraryBooks: number;
  flagsReady: number;
  equinoxCharge: number;
  equinoxChargeRequired: number;
  equinoxChallengesReady: number;
  spiceClaims: number;
  breedingEggs: number[];
  summonAttempts: number;
  sneakingLastLootedSec: number;
  sneakingCharmRolls: number;
  farmEmptyPlots: number;
  farmHighOgPlots: number;
  farmCropsOnPlots: number;
  emperorAttempts: number;
  pageReadsToday: number;
  mineheadTriesLeft: number;
  researchRollsLeft: number;
  sushiFuel: number;
  sushiFuelCapEstimate: number;
  sushiShakers: [number, number, number];
  buttonSkips: number;
  jeweledCogPulls: number;
  keyDays: { name: string; rawName: string; days: number; ready: number }[];
  coloTickets: { name: string; rawName: string; days: number; ready: number }[];
  miniBosses: { name: string; rawName: string; current: number; unlocked: boolean }[];
  poShipments: { index: number; streak: number; shield: number; completedAnOrder: boolean }[];
  forgeEmptySlots: number;
  trapsOverdue: number;
  arcadeAfkSec: number;
  unfinishedDailyTasks: number[];
  shopItemsLeft: number;
  emptyFamilyObols: number;
  companionClaimReady: boolean;
  dungeonTraitsUnpicked: number;
  guildDailyLeft: number;
  guildWeeklyLeft: number;
  owlFeathers: number;
  owlRestartCostReady: boolean;
  owlMegaRestartCostReady: boolean;
  affordableStampCount: number;
  affordableStampPercent: number;
  vialsReady: { name: string; rawName: string }[];
  mealsReady: { name: string; rawName: string }[];
  missingHats: { name: string; rawName: string }[];
  missingTrophies: { name: string; rawName: string }[];
  missingNametags: { name: string; rawName: string }[];
  buildingsReady: { name: string; index: number }[];
  refineryMissing: { saltName: string; rawName: string }[];
  refineryRankUp: { saltName: string; rawName: string }[];
  betterShopCaptains: number;
  kangarooShinyPct: number;
  kangarooFisherooReady: boolean;
  kangarooGreatestCatchReady: boolean;
  sigilsReady: { name: string; index: number }[];
  stampReducerPct: number;
  foodLustMaxed: boolean;
  holeSedimentReady: boolean;
  holeMotherlodeMaxed: boolean;
  holeHiveMaxed: boolean;
  holeEvertreeMaxed: boolean;
  holeTrenchMaxed: boolean;
  holeBraveryReady: boolean;
  holeJusticeReady: boolean;
  holeWisdomReady: boolean;
  holeBellReady: boolean;
  holeHarpReady: boolean;
  holeGrottoReady: boolean;
  holeJars: number;
  holeJarsFull: number;
  holeVillagersReady: { name: string; index: number }[];
  holeStudiesReady: { name: string; index: number }[];
  holeLayersBrokenToday: number;
  arcadeUnmaxed: { effect: string; level: number; index: number }[];
  printerFull: { name: string; rawName: string }[];
  emptyRibbonSlots: number | null;
  cookingMasteryYellow: number;
  cookingMasteryPurple: number;
  gamingSprouts: number;
  gamingSproutsCapacity: number;
  gamingDrops: number;
  gamingShovelHours: number;
  gamingSquirrelHours: number;
  gamingShovelUnlocked: boolean;
  gamingSquirrelUnlocked: boolean;
  fullStaminaCharacters: number;
  overstimLevel: number;
  legendPointsLeft: number;
  legendPointsSpent: number;
  legendMaxSpendable: number;
  masterclassCheapAvailable: number;
  masterclassCheapUsed: number;
  masterclassCheapMax: number;
  doubleClusterReady: boolean;
  jeweledCogAvailable: number;
  jeweledCogCurrent: number;
  jeweledCogMax: number;
  jeweledCogsUnlocked: boolean;
  sushiKnowledgeReady: { name: string; index: number; level: number }[];
  insightObservations: { name: string; index: number; insightLevel: number }[];
};

export type DashboardAlert = {
  world: string;
  id: string;
  title: string;
  detail?: string;
  icon: string;
};

export type AdviceSeverity = 'info' | 'warning' | 'good';

export type AdviceItem = {
  title: string;
  detail: string;
  severity: AdviceSeverity;
  current?: string;
  goal?: string;
  /** Idleon Toolbox asset path, e.g. data/ConTower8 */
  icon?: string;
  /** Extra inline icons (e.g. atom sprites for not-maxed upgrades). */
  icons?: string[];
};

export type AdviceGroup = {
  id: string;
  world: string;
  title: string;
  summary: string;
  items: AdviceItem[];
};
